<?php
$title = 'Add new field';
$this->headTitle($title);
?>
<div class="row">
<div class="col-md-2"></div>
<div class="col-md-8">
	<!-- start: FORM VALIDATION 1 PANEL -->
	<div class="panel panel-default">
		<div class="panel-heading"> <b>Add field</b> </div>
	
	<div class="panel-body">
	<?php
$form = $this->form;
$form->setAttribute('action', $this->url('attributefield', array('action' => 'add')));
$form->prepare();
echo $this->form()->openTag($form);  ?>

					<?php print $this->formRow($form->get('setId'));?>
					<fieldset>
						<div class="form-group">														
								<?php print $this->formRow($form->get('fieldName'));?>
										
						</div>
						
						<div class="form-group">
								<?php print $this->formRow($form->get('fieldType'));?>
						
						</div>
						
						<div class="form-group">
								<?php print $this->formRow($form->get('active'));?>
						
						</div>
						<div class="form-actions" align="center">
						<?php print $this->formRow($form->get('submit'));?>
						
						</div>
					</fieldset>
<?php 
//echo $this->formCollection($form);
echo $this->form()->closeTag(); 
?>
</div>
</div>
</div>
<div class="col-md-2"></div>
</div>
