<div class="footer clearfix">
			<div class="footer-inner">
				2013 &copy; clip-one by cliptheme.
			</div>
			<div class="footer-items">
				<span class="go-top"><i class="clip-chevron-up"></i></span>
			</div>
		</div>
		
		<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.0.3/jquery.min.js" type="text/javascript"></script>
        <?php echo $this->headScript()
            ->prependFile($this->basePath() . '/assets/plugins/jquery-ui/jquery-ui-1.10.2.custom.min.js')
            ->prependFile($this->basePath() . '/assets/plugins/bootstrap/js/bootstrap.min.js')
			->prependFile($this->basePath() . '/assets/plugins/blockUI/jquery.blockUI.js')
			->prependFile($this->basePath() . '/assets/plugins/iCheck/jquery.icheck.min.js')
			->prependFile($this->basePath() . '/assets/plugins/perfect-scrollbar/src/jquery.mousewheel.js')
			->prependFile($this->basePath() . '/assets/plugins/perfect-scrollbar/src/perfect-scrollbar.js')
			->prependFile($this->basePath() . '/assets/plugins/less/less-1.5.0.min.js')
			->prependFile($this->basePath() . '/assets/plugins/jquery-cookie/jquery.cookie.js')
			->prependFile($this->basePath() . '/assets/plugins/bootstrap-colorpalette/js/bootstrap-colorpalette.js');
			//->prependFile($this->basePath() . '/assets/js/main.js');
			
           // ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
           // ->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))
         ?>