	<div class="main-navigation navbar-collapse collapse">
					<!-- start: MAIN MENU TOGGLER BUTTON -->
					<div class="navigation-toggler">
						<i class="clip-chevron-left"></i>
						<i class="clip-chevron-right"></i>
					</div>
					<!-- end: MAIN MENU TOGGLER BUTTON -->
					<!-- start: MAIN NAVIGATION MENU -->
					<ul class="main-navigation-menu">
						<li>
							<a href="index.html"><i class="clip-home-3"></i>
								<span class="title"> Dashboard </span><span class="selected"></span>
							</a>
						</li>
						<li class="active open">
							<a href="javascript:void(0)"><i class="clip-screen"></i>
								<span class="title">Setting & configuration</span><i class="icon-arrow"></i>
								<span class="selected"></span>
							</a>
							<ul class="sub-menu">
								<li>
									<a href="#">
										<span class="title"> Setting #1 </span>
									</a>
								</li>
								<li>
									<a href="#">
										<span class="title"> Setting #2  </span>
									</a>
								</li>
															
							</ul>
						</li>						
						<li>
							<a href="javascript:void(0)"><i class="clip-cog-2"></i>
								<span class="title"> Player Management </span><i class="icon-arrow"></i>
								<span class="selected"></span>
							</a>
							<ul class="sub-menu">
								<li>
									<a href="ui_elements.html">
										<span class="title"> Player List </span>
									</a>
								</li>
								
							</ul>
						</li>
						<li>
							<a href="javascript:void(0)"><i class="clip-grid-6"></i>
								<span class="title"> Attributes & Category</span><i class="icon-arrow"></i>
								<span class="selected"></span>
							</a>
							<ul class="sub-menu">
								<li>
									<a href="#">
										<span class="title">Setting #1</span>
									</a>
								</li>
								<li>
									<a href="#">
										<span class="title">Setting #2</span>
									</a>
								</li>
							
							</ul>
						</li>
						<li>
							<a href="javascript:void(0)"><i class="clip-pencil"></i>
								<span class="title"> Consumable section </span><i class="icon-arrow"></i>
								<span class="selected"></span>
							</a>
							<ul class="sub-menu">
								<li>
									<a href="#">
										<span class="title">Setting #1</span>
									</a>
								</li>
								<li>
									<a href="#">
										<span class="title">Setting #2</span>
									</a>
								</li>
							</ul>
						</li>
						<li>
							<a href="javascript:void(0)"><i class="clip-user-2"></i>
								<span class="title">Tournament</span><i class="icon-arrow"></i>
								<span class="selected"></span>
							</a>
							<ul class="sub-menu">
								<li>
									<a href="#">
										<span class="title">Setting #1</span>
									</a>
								</li>
								<li>
									<a href="#">
										<span class="title">Setting #2</span>
									</a>
								</li>
							</ul>
						</li>
						<li>
							<a href="javascript:void(0)"><i class="clip-file"></i>
								<span class="title">Monetization section</span><i class="icon-arrow"></i>
								<span class="selected"></span>
							</a>
							<ul class="sub-menu">
								<li>
									<a href="#">
										<span class="title">Setting #1</span>
									</a>
								</li>
								<li>
									<a href="#">
										<span class="title">Setting #2</span>
									</a>
								</li>
							</ul>
						</li>
						<li>
							<a href="javascript:void(0)"><i class="clip-attachment-2"></i>
								<span class="title">Advertisement</span><i class="icon-arrow"></i>
								<span class="selected"></span>
							</a>
							<ul class="sub-menu">
								<li>
									<a href="#">
										<span class="title">Setting #1</span>
									</a>
								</li>
								<li>
									<a href="#">
										<span class="title">Setting #2</span>
									</a>
								</li>
							</ul>
						</li>
						
					</ul>
					<!-- end: MAIN NAVIGATION MENU -->
				</div>