<?php echo $this->doctype(); ?>

<html lang="en" class="no-js">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('ZF2 '. $this->translate('Skeleton Application'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
			 ->appendName('apple-mobile-web-app-capable', 'yes')
			  ->appendName('apple-mobile-web-app-status-bar-style', 'black')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>
		
		
		<!-- start: MAIN CSS -->
        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/assets/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/assets/plugins/bootstrap/css/bootstrap.min.css') 
                        ->prependStylesheet($this->basePath() . '/assets/plugins/font-awesome/css/font-awesome.min.css')                        
						->prependStylesheet($this->basePath() . '/assets/fonts/style.css')
						->prependStylesheet($this->basePath() . '/assets/css/main.css')
						->prependStylesheet($this->basePath() . '/assets/css/main-responsive.css')
						->prependStylesheet($this->basePath() . '/assets/plugins/iCheck/skins/all.css')
						->prependStylesheet($this->basePath() . '/assets/plugins/bootstrap-colorpalette/css/bootstrap-colorpalette.css')
						->prependStylesheet($this->basePath() . '/assets/plugins/perfect-scrollbar/src/perfect-scrollbar.css')
						->prependStylesheet($this->basePath() . '/assets/plugins/perfect-scrollbar/src/perfect-scrollbar.css')
						->prependStylesheet($this->basePath() . '/assets/css/theme_light.css')
						
						?>
						
						
	
	
		<!--[if IE 7]>
		 <link rel="stylesheet" href="/assets/plugins/font-awesome/css/font-awesome-ie7.min.css">
		<![endif]-->
		<!-- end: MAIN CSS -->
		<!-- start: CSS REQUIRED FOR THIS PAGE ONLY -->
		<!-- end: CSS REQUIRED FOR THIS PAGE ONLY -->				

        

    </head>
   <body class="login example1">
		<div class="main-login col-md-4 col-md-offset-4 col-sm-6 col-sm-offset-3">
			<div class="logo">CLIP<i class="clip-clip"></i>ONE
			</div>
			<!-- start: LOGIN BOX -->
		<?php echo $this->content; ?>
			<!-- end: LOGIN BOX -->
			<!-- start: FORGOT BOX -->
			<div class="box-forgot">
				<h3>Forget Password?</h3>
				<p>
					Enter your e-mail address below to reset your password.
				</p>
				<form class="form-forgot">
					<div class="errorHandler alert alert-danger no-display">
						<i class="fa fa-remove-sign"></i> You have some form errors. Please check below.
					</div>
					<fieldset>
						<div class="form-group">
							<span class="input-icon">
								<input type="email" class="form-control" name="email" placeholder="Email">
								<i class="fa fa-envelope"></i> </span>
						</div>
						<div class="form-actions">
							<button class="btn btn-light-grey go-back">
								<i class="fa fa-circle-arrow-left"></i> Back
							</button>
							<button type="submit" class="btn btn-bricky pull-right">
								Submit <i class="fa fa-arrow-circle-right"></i>
							</button>
						</div>
					</fieldset>
				</form>
			</div>
			<!-- end: FORGOT BOX -->
			<!-- start: REGISTER BOX -->
			<div class="box-register">
				<h3>Sign Up</h3>
				<p>
					Enter your personal details below:
				</p>
				<form class="form-register">
					<div class="errorHandler alert alert-danger no-display">
						<i class="fa fa-remove-sign"></i> You have some form errors. Please check below.
					</div>
					<fieldset>
						<div class="form-group">
							<input type="text" class="form-control" name="full_name" placeholder="Full Name">
						</div>
						<div class="form-group">
							<input type="text" class="form-control" name="address" placeholder="Address">
						</div>
						<div class="form-group">
							<input type="text" class="form-control" name="city" placeholder="City">
						</div>
						<div class="form-group">
							<div>
								<label class="radio-inline">
									<input type="radio" class="grey" value="F" name="gender">
									Female
								</label>
								<label class="radio-inline">
									<input type="radio" class="grey" value="M" name="gender">
									Male
								</label>
							</div>
						</div>
						<p>
							Enter your account details below:
						</p>
						<div class="form-group">
							<span class="input-icon">
								<input type="email" class="form-control" name="email" placeholder="Email">
								<i class="fa fa-envelope"></i> </span>
						</div>
						<div class="form-group">
							<span class="input-icon">
								<input type="password" class="form-control" id="password" name="password" placeholder="Password">
								<i class="fa fa-lock"></i> </span>
						</div>
						<div class="form-group">
							<span class="input-icon">
								<input type="password" class="form-control" name="password_again" placeholder="Password Again">
								<i class="fa fa-lock"></i> </span>
						</div>
						<div class="form-group">
							<div>
								<label for="agree" class="checkbox-inline">
									<input type="checkbox" class="grey agree" id="agree" name="agree">
									I agree to the Terms of Service and Privacy Policy
								</label>
							</div>
						</div>
						<div class="form-actions">
							<button class="btn btn-light-grey go-back">
								<i class="fa fa-circle-arrow-left"></i> Back
							</button>
							<button type="submit" class="btn btn-bricky pull-right">
								Submit <i class="fa fa-arrow-circle-right"></i>
							</button>
						</div>
					</fieldset>
				</form>
			</div>
			<!-- end: REGISTER BOX -->
			<!-- start: COPYRIGHT -->
			<div class="copyright">
				2013 &copy; clip-one by cliptheme.
			</div>
			<!-- end: COPYRIGHT -->
		</div>
		
		<!-- start: MAIN JAVASCRIPTS -->
		<!--[if lt IE 9]>
		<script src="/assets/plugins/respond.min.js"></script>
		<script src="/assets/plugins/excanvas.min.js"></script>
		<![endif]-->
		<!-- Scripts -->
		<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.0.3/jquery.min.js" type="text/javascript"></script>
        <?php echo $this->headScript()
            ->prependFile($this->basePath() . '/assets/plugins/jquery-ui/jquery-ui-1.10.2.custom.min.js')
            ->prependFile($this->basePath() . '/assets/plugins/bootstrap/js/bootstrap.min.js')
			->prependFile($this->basePath() . '/assets/plugins/blockUI/jquery.blockUI.js')
			->prependFile($this->basePath() . '/assets/plugins/iCheck/jquery.icheck.min.js')
			->prependFile($this->basePath() . '/assets/plugins/perfect-scrollbar/src/jquery.mousewheel.js')
			->prependFile($this->basePath() . '/assets/plugins/perfect-scrollbar/src/perfect-scrollbar.js')
			->prependFile($this->basePath() . '/assets/plugins/less/less-1.5.0.min.js')
			->prependFile($this->basePath() . '/assets/plugins/jquery-cookie/jquery.cookie.js')
			->prependFile($this->basePath() . '/assets/plugins/bootstrap-colorpalette/js/bootstrap-colorpalette.js')
			->prependFile($this->basePath() . '/assets/plugins/jquery-validation/dist/jquery.validate.min.js')
			->prependFile($this->basePath() . '/assets/js/login.js');
			
			//->prependFile($this->basePath() . '/assets/js/main.js');
			
           // ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
           // ->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))
         ?>
		<script src="<?php print $this->basePath() ; ?>/assets/js/main.js"></script>
		
		<!-- /container -->
		<script>
			jQuery(document).ready(function() {
				Main.init();
				Login.init();
			});
		</script>
				
        <?php //echo $this->inlineScript() ?>
		
		
    </body>
</html>
