
<div class="page-header">
<h1>Form Elements <small>common form elements and layouts</small></h1>

</div>



<?php if(count($flashMessages)) : ?>
			<div class="row">
			<div class="col-md-12">
					<div class="alert alert-success">
					<button class="close" data-dismiss="alert">
					
					</button>
					<i class="fa fa-check-circle"></i>
					<?php foreach ($flashMessages as $msg) : ?>
					 <?php echo $msg; ?>
					<?php endforeach; ?>
					</div>
			</div>
			</div>
<?php endif; ?>	




<div class="row">
<div class="col-md-2"></div>
<div class="col-md-8">
	<!-- start: FORM VALIDATION 1 PANEL -->
	<div class="panel panel-default">
		<div class="panel-heading"><i class="fa fa-external-link-square"></i> <b>Send mail to the subscribers</b> </div>
	
		<div class="panel-body">
			<?php
			$form = $this->form;
			$form->setAttribute('action', $this->url('admin', array('action' => 'mailsubscribers')));
			$form->prepare();
			echo $this->form()->openTag($form);
			
			?>
			<fieldset>
			
								
			<div class="form-group">
			<label class="control-label">
			 Put your email message:
			</label>
			<?php print $this->formRow($form->get('content'));?>
			</div>
		


			
			
			<div class="form-actions" align="right">
			<?php print $this->formRow($form->get('submit'));?>
			</div>
			</fieldset>
			
		<?php echo $this->form()->closeTag(); ?>
		</div>
</div>
</div>
<div class="col-md-2"></div>
</div>
