<?php
// module/Album/view/album/album/index.phtml:

$title = 'Attribute set List';
$this->headTitle($title);
?><?php //echo $this->escapeHtml($title); ?>
<div class="page-header">
<p><a href="<?php print $this->basePath(); ?>/admin/missions/add" class="btn btn-primary"><i class="fa fa-plus"></i> Add New Mission</a></p>
</div>	
	 
<?php if(count($flashMessages)) : ?>
			<div class="row">
			<div class="col-md-12">
					<div class="alert alert-success">
					<button class="close" data-dismiss="alert">
					×
					</button>
					<i class="fa fa-check-circle"></i>
					<?php foreach ($flashMessages as $msg) : ?>
					<?php echo $msg; ?>
					<?php endforeach; ?>
					</div>
			</div>
			</div>
<?php endif; ?>	 
	 
	 
	 
	 
	 
	 
	 
	 
	<div class="row">
	<div class="col-md-12">
	<div class="panel panel-default">
	<div class="panel-heading">
	<i class="fa fa-external-link-square"></i>
	<span style="padding-left:25px;">Missions List</span>
	<div class="panel-tools">
	<a class="btn btn-xs btn-link panel-collapse collapses" href="#">
	</a>
	<a class="btn btn-xs btn-link panel-config" href="#panel-config" data-toggle="modal">
	<i class="fa fa-wrench"></i>
	</a>
	<a class="btn btn-xs btn-link panel-refresh" href="#">
	<i class="fa fa-refresh"></i>
	</a>
	<a class="btn btn-xs btn-link panel-expand" href="#">
	<i class="fa fa-resize-full"></i>
	</a>
	<a class="btn btn-xs btn-link panel-close" href="#">
	<i class="fa fa-times"></i>
	</a>
	</div>
	</div>
	<div class="panel-body">
	<table class="table table-hover" id="sample-table-1">		
	<thead>
	<tr>
	<th class="center">#</th>
	<th>Name</th>
	<th>Duration</th>
	<th>Points Required(Min)</th>	

	<th class="hidden-xs">Difficulty Levels</th>
	<th class="hidden-xs">Premium Currency</th>
	<th class="hidden-xs">Normal Currency</th>
	<th class="hidden-xs">XP Rewarded</th>
	<th class="hidden-xs">Status</th>

	<th class="hidden-xs"></th>
	</tr>
	</thead>
	
	
	<tbody>
	<?php if(count($missions) <=0 )  { ?>
	<tr><td class="left" colspan="10" ><p class="text-danger">No results found !</p></td></tr>
	
	<?php } else { ?>
	<?php foreach($missions as $row) : ?>
	<tr>
	<td class="center"><?php print $row['id']; ?></td>
	<td class="hidden-xs"><a href="<?php print $this->basePath(); ?>/admin/missions/details/<?php print $row['id']; ?>"><?php echo $this->escapeHtml($row['name']);?></a></td>
	<td class="hidden-xs"><?php print $row['duration'];?></td>
	<td class="hidden-xs"><?php print $row['minimum_points_required']; ?></td>

	<td class="hidden-xs"><?php print $row['difficulty_level']; ?></td>
	<td class="hidden-xs"><?php print $row['premium_currency_rewarded']; ?></td>
	<td class="hidden-xs"><?php print $row['normal_currency_rewarded']; ?></td>
	<td class="hidden-xs"><?php print $row['xp_rewarded']; ?></td>
	<td class="hidden-xs" id="changeStatus<?php print $row['id'];?>"><?php print ($row['active'] == 1) ? '<span id="'.$row['id'].'" class="label label-sm label-success change_status" onClick=clickMe(this,\'deactive\')>Active</span>' : '<span id="'.$row->id.'" class="label label-sm label-danger change_status" onClick=clickMe(this,\'active\')>Expired</span>'; ?>
	</td>

	<td class="center">	
	<div class="visible-md visible-lg hidden-sm hidden-xs">
	<a href="<?php print $this->basePath(); ?>/admin/missions/edit/<?php print $row['id']; ?>" class="btn btn-xs btn-teal tooltips" data-placement="top" data-original-title="Edit"><i class="fa fa-edit"></i></a>
	
	<a href="<?php print $this->basePath(); ?>/admin/missions/delete/<?php print $row['id']; ?>" class="btn btn-xs btn-bricky tooltips" data-placement="top" data-original-title="Remove"><i class="fa fa-times fa fa-white"></i></a>
	</div>
	<div class="visible-xs visible-sm hidden-md hidden-lg">
	<div class="btn-group">
	<a class="btn btn-primary dropdown-toggle btn-sm" data-toggle="dropdown" href="#">
	<i class="fa fa-cog"></i> <span class="caret"></span>
	</a>
	<ul role="menu" class="dropdown-menu pull-right">
	
	<li role="presentation">
	<a role="menuitem" tabindex="-1" href="<?php print $this->basePath(); ?>/admin/missions/edit/<?php print $row['id']; ?>">
	<i class="fa fa-edit"></i> Edit
	</a>
	</li>

	<li role="presentation">
	<a role="menuitem" tabindex="-1" href="<?php print $this->basePath(); ?>/admin/missions/delete/<?php print $row['id']; ?>">
	<i class="fa fa-times"></i> Remove
	</a>
	</li>
	</ul>
	</div>
	</div>

	</td>

	</tr>	
	<?php endforeach; ?>
	<?php } ?>
	
	</tbody>
	</table>
	</div>
	</div>





	</div></div>











 
 
 
 
 


 
 
 
 
 
 
 
 
 
 
 
