	<div class="main-navigation navbar-collapse collapse">
					<!-- start: MAIN MENU TOGGLER BUTTON -->
					<div class="navigation-toggler">
						<i class="clip-chevron-left"></i>
						<i class="clip-chevron-right"></i>
					</div>
					<!-- end: MAIN MENU TOGGLER BUTTON -->
					<!-- start: MAIN NAVIGATION MENU -->
					<ul class="main-navigation-menu">
						<li>
							<a href="/huntinggame/public/admin/dashboard"><i class="clip-home-3"></i>
								<span class="title"> Dashboard </span><span class="selected"></span>
							</a>
						</li>
						<li class="active open">
							<a href="javascript:void(0)"><i class="clip-screen"></i>
								<span class="title">Setting & configuration</span><i class="icon-arrow"></i>
								<span class="selected"></span>
							</a>
							<ul class="sub-menu">
							
							<li><a href="/huntinggame/public/admin/region/index"><span class="title"> Regions  </span></a></li>
							<li><a href="/huntinggame/public/admin/hunttype/index"><span class="title"> Hunt Type </span></a></li>								
							<li><a href="/huntinggame/public/admin/suggestion/index"><span class="title"> Hunt Suggestions </span></a></li>
							<li><a href="/huntinggame/public/admin/light/index"><span class="title"> Light Conditions </span></a></li>

							<li><a href="/huntinggame/public/admin/kill-type/index"><span class="title">Kill Type</span></a></li>
							<li><a href="/huntinggame/public/admin/shorthand-target/index"><span class="title">Shorthand Target Type</span></a></li>
							<li><a href="/huntinggame/public/admin/player-position/index"><span class="title">Player Positions</span></a></li>	






							
							<li>
							<a href="javascript:;"> Deer Information <i class="icon-arrow"></i> </a>
							<ul class="sub-menu">
							<li><a href="<?php print $this->basePath(); ?>/admin/deer-activity/index">Deer Activity</a></li>						
							<li><a href="<?php print $this->basePath(); ?>/admin/deer-size/index">Deer Size</a></li>
							<li><a href="<?php print $this->basePath(); ?>/admin/deer-facing/index">Deer Facing</a></li>
							<li><a href="<?php print $this->basePath(); ?>/admin/deer-position/index">Deer Positions</a></li>
							<li><a href="/huntinggame/public/admin/deerinfo/index">Deer Information</a></li>		
							</ul>
							</li>
							
							
							
							
							
							
							
							
								<li>
									<a href="/huntinggame/public/admin/haircolor/index">
										<span class="title"> Hair Color </span>
									</a>
								</li>
								<li>
									<a href="/huntinggame/public/admin/skincolor/index">
										<span class="title"> Skin Color  </span>
									</a>
								</li>
								<li><a href="<?php print $this->basePath() ; ?>/admin/face-color/index"><span class="title"> Face Color  </span></a></li>
								<li><a href="<?php print $this->basePath() ; ?>/admin/player-rank/index"><span class="title"> Player Rank System  </span></a></li>								
								
								
								
								
								
								
															
							</ul>
						</li>						
						<li>
							<a href="javascript:void(0)"><i class="clip-cog-2"></i>
								<span class="title"> Player Management </span><i class="icon-arrow"></i>
								<span class="selected"></span>
							</a>
							<ul class="sub-menu">
								<li>
									<a href="/huntinggame/public/admin/player/index">
										<span class="title"> Player List </span>
									</a>
								</li>
								
							</ul>
						</li>
						<li>
							<a href="javascript:void(0)"><i class="clip-grid-6"></i>
								<span class="title"> Attributes & Category</span><i class="icon-arrow"></i>
								<span class="selected"></span>
							</a>
							<ul class="sub-menu">
								<li>
									<a href="/huntinggame/public/admin/attributeset/index">
										<span class="title">Attribute Set</span>
									</a>
								</li>
								<li>
									<a href="/huntinggame/public/admin/weapon/index">
										<span class="title">Weapon</span>
									</a>
								</li>
							
							</ul>
						</li>
											<li>
							<a href="javascript:void(0)"><i class="clip-pencil"></i>
								<span class="title"> Regions & Clothings</span><i class="icon-arrow"></i>
								<span class="selected"></span>
							</a>
							<ul class="sub-menu">
								<li>
									<a href="/huntinggame/public/admin/attributeset/index">
										<span class="title">Attribute Set</span>
									</a>
								</li>							
							
								<li>
									<a href="/huntinggame/public/admin/clothing/index">
										<span class="title">Clothings</span>
									</a>
								</li>
								
								
							</ul>
						</li>
						
						
						
						
						
						<!--
						
						<li>
							<a href="javascript:void(0)"><i class="clip-pencil"></i>
								<span class="title"> Consumable section </span><i class="icon-arrow"></i>
								<span class="selected"></span>
							</a>
							<ul class="sub-menu">
								<li>
									<a href="#">
										<span class="title">Setting #1</span>
									</a>
								</li>
								<li>
									<a href="#">
										<span class="title">Setting #2</span>
									</a>
								</li>
							</ul>
						</li>
						
						-->
						
						
						<!--
						<li>
							<a href="javascript:void(0)"><i class="clip-user-2"></i>
								<span class="title">Tournament</span><i class="icon-arrow"></i>
								<span class="selected"></span>
							</a>
							<ul class="sub-menu">
								<li>
									<a href="<?php //print $this->basePath(); ?>/admin/tournament/index">
										<span class="title">Tournament List</span>
									</a>
								</li>
								<li>
									<a href="#">
										<span class="title">Setting #2</span>
									</a>
								</li>
							</ul>
						</li>
						-->
						
						<li>
							<a href="javascript:void(0)"><i class="clip-user-2"></i>
								<span class="title">Tournament</span><i class="icon-arrow"></i>
								<span class="selected"></span>
							</a>
							<ul class="sub-menu">
								<li>
									<a href="/huntinggame/public/admin/tournament/index">
										<span class="title">Manage Tournament</span>
									</a>
								</li>
								<li>
									<a href="/huntinggame/public/admin/missions/index">
										<span class="title">Manage Missions</span>
									</a>
								</li>
							</ul>
						</li>						
						
						
						
						
						
						
						
						
						
						
						
						
						
						<li>
							<a href="javascript:void(0)"><i class="clip-file"></i>
								<span class="title">Monetization section</span><i class="icon-arrow"></i>
								<span class="selected"></span>
							</a>
							<ul class="sub-menu">
								<li>
									<a href="/huntinggame/public/admin/bank/index">
										<span class="title">Banks</span>
									</a>
								</li>
								<li>
									<a href="<?php print $this->basePath() ; ?>/admin/advertisement/index">
										<span class="title">Advertisement<?php //echo $this->basePath(); ?></span>
									</a>
								</li>
							</ul>
						</li>
						
						<li>
							<a href="javascript:void(0)"><i class="clip-attachment-2"></i>
								<span class="title">Reports</span><i class="icon-arrow"></i>
								<span class="selected"></span>
							</a>
							<ul class="sub-menu">
								<li><a href="<?php print $this->basePath();?>/admin/bank-report"><span class="title">Bank Transaction Report</span></a></li>
								<li><a href="<?php print $this->basePath();?>/admin/ad-report"><span class="title">Advertisement Report</span></a></li>	
							</ul>
						</li>
						
					<li class="active open">
					<a href="javascript:void(0)"><i class="clip-pencil"></i>
					<span class="title">CMS</span><i class="icon-arrow"></i>
					<span class="selected"></span>
					</a>
					<ul class="sub-menu" >
					<li><a href="<?php print $this->basePath();?>/admin/pages"><span class="title">Basic Pages</span></a></li>
					<li><a href="<?php print $this->basePath();?>/admin/game-video/index"><span class="title">Game Video</span></a></li>
					<li><a href="<?php print $this->basePath();?>/admin/interview-video/index"><span class="title">Interview Video</span></a></li>
					<li><a href="<?php print $this->basePath();?>/admin/offers/index"><span class="title">Offers</span></a></li>
					<li><a href="<?php print $this->basePath();?>/admin/screen-shots/index"><span class="title">Manage ScreenShots</span></a></li>
					<li><a href="<?php print $this->basePath();?>/admin/news/index"><span class="title">News</span></a></li>
					<li><a href="<?php print $this->basePath();?>/admin/img-slider/index"><span class="title">Gallery For Slider</span></a></li>
					<li><a href="<?php print $this->basePath();?>/admin/sponsor/index"><span class="title">Manage Sponsor</span></a></li>
					<li><a href="<?php print $this->basePath();?>/admin/others-game/index"><span class="title">Others Game</span></a></li>
					<li><a href="<?php print $this->basePath();?>/admin/subscribe"><span class="title">Manage Subscribers</span></a></li>
					</ul>
					</li>							
						
						
						
						
						
						
						
						
						
					</ul>
					<!-- end: MAIN NAVIGATION MENU -->
				</div>