<?php
//$getRow= $this->getData;
$title = "Edit Hunt-Club-Game" ; 
$this->headTitle($title);
?>

<div class="row">
<div class="col-md-2"></div>
<div class="col-md-8">
	<!-- start: FORM VALIDATION 1 PANEL -->
	<div class="panel panel-default">
		<div class="panel-heading"> <b>Edit  Hunt-Club-Game </b> </div>
	
		<div class="panel-body">
			<?php
			$form = $this->form;
			$form->setAttribute('action', $this->url('hunt-club-game', array('action' => 'edit' ,  'id' => $id)));
			$form->prepare();
			echo $this->form()->openTag($form);
			echo $this->formHidden($form->get('id'));
			?>
			<fieldset>
			
			<div class="form-group">
			<?php print $this->formRow($form->get('hunt_clubs_id'));?>
			</div>
			
			<div class="form-group">
			<?php print $this->formRow($form->get('light_conditions_id'));?>
			</div>
			
			<div class="form-group">
			<?php print $this->formRow($form->get('regions_id'));?>
			</div>
			
			<div class="form-group">
			<?php print $this->formRow($form->get('number_of_animals'));?>
			</div>			
			
			<div class="form-group">
			<?php print $this->formRow($form->get('time_to_complete'));?>
			</div>				
			
			
			
			
			

			<div class="form-group">
			<?php print $this->formRow($form->get('active'));?>
			</div>
			
			<div class="form-actions" align="right">
			<?php print $this->formRow($form->get('submit'));?>
			</div>
			</fieldset>
			
		<?php echo $this->form()->closeTag(); ?>
		</div>
</div>
</div>
<div class="col-md-2"></div>
</div>
