<?php
// module/Album/view/album/album/index.phtml:
$title = 'Attribute set List';
$this->headTitle($title);
$setId = $this->setID;
?>
<?php //echo $this->escapeHtml($title); ?>
<div class="row">
<div class="col-sm-12"><p><a href="<?php print $this->basePath(); ?>/admin/clothing/add" class="btn btn-primary"><i class="fa fa-plus"></i>Add  Attribute Field Value</a></p></div>
</div>	







<!--
<div class="row">
<div class="col-sm-6"><p><a href="/admin/clothing/add" class="btn btn-primary"><i class="fa fa-plus"></i>Add  Attribute Field Value</a></p></div>
<div class="col-sm-6">
	<div class="form-group">
	<select class="form-control" id="form-field-select-1-sortby">
	<option value="0">Sort By Type</option>
	<?php //foreach($attributeSets as $attributeSetsVal) : ?>
	<option value="<?php //print $attributeSetsVal->id; ?>" <?php //if($setId == $attributeSetsVal->id) :?> selected <?php //endif;?> ><?php //print $this->escapeHtml($attributeSetsVal->name); ?></option>
	<?php //endforeach; ?>

	</select>
	</div>

</div>
</div>	--> 
	 
	<div class="row">
	<div class="col-md-12">
	<div class="panel panel-default">
	<div class="panel-heading">
	<i class="fa fa-external-link-square"></i>
	<span style="padding-left:25px;">Entity-Value Lists </span>
	<div class="panel-tools">
	<a class="btn btn-xs btn-link panel-collapse collapses" href="#">
	</a>
	<a class="btn btn-xs btn-link panel-config" href="#panel-config" data-toggle="modal">
	<i class="fa fa-wrench"></i>
	</a>
	<a class="btn btn-xs btn-link panel-refresh" href="#">
	<i class="fa fa-refresh"></i>
	</a>
	<a class="btn btn-xs btn-link panel-expand" href="#">
	<i class="fa fa-resize-full"></i>
	</a>
	<a class="btn btn-xs btn-link panel-close" href="#">
	<i class="fa fa-times"></i>
	</a>
	</div>
	</div>
	<div class="panel-body">
	<table class="table table-hover" id="sample-table-1">		
	<thead>
	<tr>
	<th class="center">#</th>
	<th>Name</th>	
	<th>Price($)</th>
	<th>Type</th>	
	<th class="hidden-xs">Status</th>
	<th class="hidden-xs"></th>
	</tr>
	</thead>
	<tbody>
	<?php if(count($weapons) > 0  ) : ?>
	<?php foreach($weapons as $weapon) : ?>
	<tr>
	<td class="center"><?php print $weapon['id']; ?></td>	
	<td class="hidden-xs"><?php echo $this->escapeHtml($weapon['name']);?></td>
	<td class="hidden-xs"><?php echo $this->escapeHtml($weapon['price_gold']);?></td>
	<td class="hidden-xs"><?php echo $this->escapeHtml($weapon['setName']);?></td>
	<td class="hidden-xs" id="changeStatus<?php print $weapon['id'];?>"><?php print ($weapon['active'] == 1) ? '<span id="'.$weapon['id'].'" class="label label-sm label-success change_status" onClick=clickMe(this,\'deactive\')>Active</span>' : '<span id="'.$weapon->id.'" class="label label-sm label-danger change_status" onClick=clickMe(this,\'active\')>Expired</span>'; ?>
	
	</td>
		<td class="center">
	
	
	<div class="visible-md visible-lg hidden-sm hidden-xs">
	<a href="<?php print $this->basePath(); ?>/admin/clothing/edit/<?php print $weapon['id']; ?>" class="btn btn-xs btn-teal tooltips" data-placement="top" data-original-title="Edit"><i class="fa fa-edit"></i></a>
	
	<a href="<?php print $this->basePath(); ?>/admin/clothing/delete/<?php print $weapon['id']; ?>" class="btn btn-xs btn-bricky tooltips" data-placement="top" data-original-title="Remove"><i class="fa fa-times fa fa-white"></i></a>
	</div>
	<div class="visible-xs visible-sm hidden-md hidden-lg">
	<div class="btn-group">
	<a class="btn btn-primary dropdown-toggle btn-sm" data-toggle="dropdown" href="#">
	<i class="fa fa-cog"></i> <span class="caret"></span>
	</a>
	<ul role="menu" class="dropdown-menu pull-right">
	
	<li role="presentation">
	<a role="menuitem" tabindex="-1" href="<?php print $this->basePath(); ?>/admin/clothing/edit/<?php print $weapon['id']; ?>">
	<i class="fa fa-edit"></i> Edit
	</a>
	</li>

	<li role="presentation">
	<a role="menuitem" tabindex="-1" href="<?php print $this->basePath(); ?>/admin/clothing/delete/<?php print $weapon['id']; ?>">
	<i class="fa fa-times"></i> Remove
	</a>
	</li>
	</ul>
	</div>
	</div>
	
	
	
	
	
	
	
	</td>
	
	
	
	
	
	
	
	
	</tr>
	<?php endforeach; ?>
	<?php else:?>
					<tr>
						<td class="center" colspan="5">
							<div class="alert alert-danger">				
							<i class="fa fa-times-circle"></i>
							<strong>Sorry !</strong> No Results Found.
							</div>
						</td>	
					</tr>
	<?php endif; ?>
	</tbody>
	</table>
	</div>
	</div>





	</div></div>











 
 
 
 
 


 
 
 
 
 
 
 
 
 
 
 
