<?php
// module/Album/view/album/album/index.phtml:

$title = 'Face Color List';
$this->headTitle($title);
?><?php //echo $this->escapeHtml($title); ?>
<div class="page-header">

<h1>Player Rank System<small>common form elements and layouts</small></h1> 
</div>


<p>
<a href="<?php print $this->basePath();?>/admin/player-rank/add" class="btn btn-primary"><i class="fa fa-plus"></i> Add New</a>
		
</p>
<?php if(count($flashMessages)) : ?>
			<div class="row">
					<div class="col-md-12">
							<div class="alert alert-success">
							<button class="close" data-dismiss="alert">
							×
							</button>
							<i class="fa fa-check-circle"></i>
							<?php foreach ($flashMessages as $msg) : ?>
							 <?php echo $msg; ?>
							<?php endforeach; ?>
							</div>
					</div>
			</div>
<?php endif; ?>	
		
		
		
		
		
	<div class="row">
	<div class="col-md-12">
	<div class="panel panel-default">
	<div class="panel-heading">
	<i class="fa fa-external-link-square"></i> <b>Player Ranks Badges</b>
	
	<div class="panel-tools">
	<a class="btn btn-xs btn-link panel-collapse collapses" href="#">
	</a>
	<a class="btn btn-xs btn-link panel-config" href="#panel-config" data-toggle="modal">
	<i class="fa fa-wrench"></i>
	</a>
	<a class="btn btn-xs btn-link panel-refresh" href="#">
	<i class="fa fa-refresh"></i>
	</a>
	<a class="btn btn-xs btn-link panel-expand" href="#">
	<i class="fa fa-resize-full"></i>
	</a>
	<a class="btn btn-xs btn-link panel-close" href="#">
	<i class="fa fa-times"></i>
	</a>
	</div>
	</div>
	<div class="panel-body">
	<table class="table table-hover" id="sample-table-1">		
	<thead>
	<tr>
	<th class="center">#</th>
	<th>Name</th>
	<th class="center">Badge</th>
	<th class="center">Min Exp</th>
	<th class="center">Max Exp</th>
	<th class="hidden-xs">Status</th>
	<th></th>
	</tr>
	</thead>
	<tbody>
	<?php if( 0 === $rows->count() ) { ?> <tr> <td colspan="4" class="center" > <code>Empty records found ! </code> </td> </tr> <?php } else { ?>
	<?php foreach($rows as $val) : ?>
	<tr>
	<td class="center"><?php print $val->id; ?></td>
	<td ><?php echo $this->escapeHtml($val->name);?></td>
	<td class="center"><img src="/huntinggame/public/upload/thumb/<?php print $val->field_icon; ?>" /> </td>
	<td class="center"><?php print $val->min_exp; ?></td>
	<td class="center"><?php print $val->max_exp; ?></td>
	
	<td class="hidden-xs">
	<?php print ($val->active == 1) ? '<span class="label label-sm label-success">Active</span>' : '<span class="label label-sm label-danger">Expired</span>'; ?>	
	</td>
	
	<td class="center">
	
	
	<div class="visible-md visible-lg hidden-sm hidden-xs">
	<a href="<?php print $this->basePath();?>/admin/player-rank/edit/<?php print $val->id; ?>" class="btn btn-xs btn-teal tooltips" data-placement="top" data-original-title="Edit"><i class="fa fa-edit"></i></a>
	
	<a href="<?php print $this->basePath();?>/admin/player-rank/delete/<?php print $val->id; ?>" class="btn btn-xs btn-bricky tooltips" data-placement="top" data-original-title="Remove"><i class="fa fa-times fa fa-white"></i></a>
	</div>
	<div class="visible-xs visible-sm hidden-md hidden-lg">
	<div class="btn-group">
	<a class="btn btn-primary dropdown-toggle btn-sm" data-toggle="dropdown" href="#">
	<i class="fa fa-cog"></i> <span class="caret"></span>
	</a>
	<ul role="menu" class="dropdown-menu pull-right">
	
	<li role="presentation">
	<a role="menuitem" tabindex="-1" href="<?php print $this->basePath();?>/admin/player-rank/edit/<?php print $val->id; ?>">
	<i class="fa fa-edit"></i> Edit
	</a>
	</li>

	<li role="presentation">
	<a role="menuitem" tabindex="-1" href="<?php print $this->basePath();?>/admin/player-rank/delete/<?php print $val->id; ?>">
	<i class="fa fa-times"></i> Remove
	</a>
	</li>
	</ul>
	</div>
	</div>
	
	
	
	
	
	
	
	</td>

	</tr>
	<?php endforeach; ?>
	<?php } ?>
	</tbody>
	</table>
	</div>
	</div>





	</div></div>











 
 
 
 
 


 
 
 
 
 
 
 
 
 
 
 
