










<?php if ($this->pageCount): ?>
<div class="col-md-12">

    <div class="dataTables_paginate paging_bootstrap" style="float: right;">
        <ul class="pagination">
            <!-- Previous page link -->
            <?php if (isset($this->previous)): ?>
                <li class="prev">
                    <a href="<?php echo $this->url($this->route); ?>?page=<?php echo $this->previous; ?>">
                        <i class="icon-double-angle-left"></i>
                    </a>
                </li>
            <?php else: ?>
                <li class="prev">
                    <a href="#">
                        <i class="icon-double-angle-left"></i>
                    </a>
                </li>
            <?php endif; ?>
            <!-- Numbered page links -->
            <?php foreach ($this->pagesInRange as $page): ?>
                <?php if ($page != $this->current): ?>
                    <li >
                        <a href="<?php echo $this->url($this->route);?>?page=<?php echo $page; ?>">
                            <?php echo $page; ?>
                        </a>
                    </li>
                <?php else: ?>
                    <li class="active">
                        <a href="#"><?php echo $page; ?></a>
                    </li>
                <?php endif; ?>
            <?php endforeach; ?>

            <!-- Next page link -->
            <?php if (isset($this->next)): ?>
                <li class="next">
                    <a href="<?php echo $this->url($this->route); ?>?page=<?php echo $this->next; ?>">
                        <i class="icon-double-angle-right"></i> 
                    </a>
                </li>
            <?php else: ?>
                <li class="disabled">
                    <a href="#">
                        <i class="icon-double-angle-right"></i> 
                    </a>
                </li>
            <?php endif; ?>
        </ul>
    </div>
	
	
	</div>
<?php endif; ?>
