<div class="per_content_area">
<h2 class="no_mrg"><img src="<?php print $this->basePath(); ?>/frontend/images/heading_icon.png" ><?php if( $this->basic_pages ) print $this->basic_pages->title ; ?></h2>

<?php if( $this->basic_pages->seo_title == 'development-team' ): ?>
 <p class="dev_pic"><img src="<?php print $this->basePath(); ?>/upload/<?php print  $this->basic_pages->field_image; ?>" alt="development-team"></p>
<?php endif; ?>
<?php if( $this->basic_pages ) print $this->basic_pages->content ; ?>


<div class="clearfix"></div>
</p>
</div>





	
	
	
	
	
	
	
	
	
	
	
	
	
	







