<?php
// module/Album/view/album/album/index.phtml:

$title = 'My albums';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>



<table class="table">
<tr>
    <th>Title</th>
    <th>Artist</th>
    <th>&nbsp;</th>
</tr>
<?php foreach($players as $player1) : ?>
<tr>
    <td><?php echo $this->escapeHtml($player1->name);?></td>
    <td><?php echo $this->escapeHtml($player1->gender);?></td>    <td>
        <a href="<?php echo $this->url('admin',
            array('action'=>'edit', 'id' => $player1->id));?>">Edit</a>
        <a href="<?php echo $this->url('admin',
            array('action'=>'delete', 'id' => $player1->id));?>">Delete</a>
    </td>
</tr>
<?php endforeach; ?>
</table>

 
 
 
 
 


 
 
 
 
 
 
 
 
 
 
 
