<?php
// module/Album/view/album/album/index.phtml:

$title = 'Banks';
$this->headTitle($title);
?><?php //echo $this->escapeHtml($title); ?>
<?php //echo $this->basePath(); ?>
<p><a href="/huntinggame/public/admin/bank/add" class="btn btn-primary"><i class="fa fa-plus"></i>Add New </a></p>
<?php if(count($flashMessages)) : ?>
			<div class="row">
			<div class="col-md-12">
					<div class="alert alert-success">
					<button class="close" data-dismiss="alert">
					×
					</button>
					<i class="fa fa-check-circle"></i>
					<?php foreach ($flashMessages as $msg) : ?>
					<strong></strong> <?php echo $msg; ?>
					<?php endforeach; ?>
					</div>
			</div>
			</div>
<?php endif; ?>






	<div class="row">
	<div class="col-md-12">
	<div class="panel panel-default">
	<div class="panel-heading">
	<i class="fa fa-external-link-square"></i>
	<span style="padding-left:25px;">Bank List</span>
	<div class="panel-tools">
	<a class="btn btn-xs btn-link panel-collapse collapses" href="#">
	</a>
	<a class="btn btn-xs btn-link panel-config" href="#panel-config" data-toggle="modal">
	<i class="fa fa-wrench"></i>
	</a>
	<a class="btn btn-xs btn-link panel-refresh" href="#">
	<i class="fa fa-refresh"></i>
	</a>
	<a class="btn btn-xs btn-link panel-expand" href="#">
	<i class="fa fa-resize-full"></i>
	</a>
	<a class="btn btn-xs btn-link panel-close" href="#">
	<i class="fa fa-times"></i>
	</a>
	</div>
	</div>
	
	<div class="panel-body">
	<table class="table table-hover" id="sample-table-1">		
	<thead>
	<tr>
	<th class="center">#</th>
	<th>Pack Type</th>
	<th>Bucks</th>
	<th>Gold Coins</th>	
	<th>Real Money In($)</th>
	<th>Created On</th>
	<th class="hidden-xs">Status</th>
	<th></th>
	<th></th>
	</tr>
	</thead>
	<tbody>
	<?php foreach($bank as $bank) : ?>
	<tr>
	<td class="center"><?php print $bank->id; ?></td>
	<td class="hidden-xs"><?php print $this->escapeHtml($bank->name);?></td>
	<td class="hidden-xs"><?php print $this->escapeHtml($bank->bucks);?></td>
	<td class="hidden-xs"><?php print $this->escapeHtml($bank->gold_coins);?></td>	
	<td class="hidden-xs "><?php print $this->escapeHtml($bank->price);?></td>
	<td class="hidden-xs"><?php print date("m/d/Y" , strtotime($bank->created_on)) ;?></td>
	<td class="hidden-xs"><?php print ($bank->active == 1) ? '<span class="label label-sm label-success">Active</span>' : '<span class="label label-sm label-danger">Expired</span>'; ?>
	<td class="center"><?php if($bank->price == '0.00') : ?>
	<a href="/admin/bank/add/<?php print $bank->id; ?>" class="btn btn-primary btn-xs"><i class="fa fa-plus"></i>Add More</a> <?php endif;?>
	</td>										
	
	</td>
	
	<td class="center">
	
	
	<div class="visible-md visible-lg hidden-sm hidden-xs">
	<a href="/huntinggame/public/admin/bank/edit/<?php print $bank->id; ?>" class="btn btn-xs btn-teal tooltips" data-placement="top" data-original-title="Edit"><i class="fa fa-edit"></i></a>
	
	<a href="/huntinggame/public/admin/bank/delete/<?php print $bank->id; ?>" class="btn btn-xs btn-bricky tooltips" data-placement="top" data-original-title="Remove"><i class="fa fa-times fa fa-white"></i></a>
	</div>
	<div class="visible-xs visible-sm hidden-md hidden-lg">
	<div class="btn-group">
	<a class="btn btn-primary dropdown-toggle btn-sm" data-toggle="dropdown" href="#">
	<i class="fa fa-cog"></i> <span class="caret"></span>
	</a>
	<ul role="menu" class="dropdown-menu pull-right">
	
	<li role="presentation">
	<a role="menuitem" tabindex="-1" href="/huntinggame/public/admin/bank/edit/<?php print $bank->id; ?>">
	<i class="fa fa-edit"></i> Edit
	</a>
	</li>

	<li role="presentation">
	<a role="menuitem" tabindex="-1" href="/huntinggame/public/admin/bank/delete/<?php print $bank->id; ?>">
	<i class="fa fa-times"></i> Remove
	</a>
	</li>
	</ul>
	</div>
	</div>
	
	
	
	
	
	
	
	</td>

	</tr>
	<?php endforeach; ?>
	</tbody>
	</table>
	</div>
	</div>





	</div></div>











 
 
 
 
 


 
 
 
 
 
 
 
 
 
 
 
