<?php
// module/Album/view/album/album/index.phtml:

$title = 'Skin Color List';
$this->headTitle($title);
?><?php //echo $this->escapeHtml($title); ?>
<p><a href="<?php echo $this->basePath(); ?>/admin/skincolor/add" class="btn btn-primary"><i class="fa fa-plus"></i>
		Add New Skin Color</a></p>
	<div class="row">
	<div class="col-md-12">
	<div class="panel panel-default">
	<div class="panel-heading">
	<i class="fa fa-external-link-square"></i>
	<span style="padding-left:25px;">Skin Color List</span>
	<div class="panel-tools">
	<a class="btn btn-xs btn-link panel-collapse collapses" href="#">
	</a>
	<a class="btn btn-xs btn-link panel-config" href="#panel-config" data-toggle="modal">
	<i class="fa fa-wrench"></i>
	</a>
	<a class="btn btn-xs btn-link panel-refresh" href="#">
	<i class="fa fa-refresh"></i>
	</a>
	<a class="btn btn-xs btn-link panel-expand" href="#">
	<i class="fa fa-resize-full"></i>
	</a>
	<a class="btn btn-xs btn-link panel-close" href="#">
	<i class="fa fa-times"></i>
	</a>
	</div>
	</div>
	<div class="panel-body">
	<table class="table table-hover" id="sample-table-1">		
	<thead>
	<tr>
	<th class="center">#</th>
	<th>Name</th>
	<th class="hidden-xs">Status</th>
	<th></th>
	</tr>
	</thead>
	<tbody>
	<?php foreach($skincolors as $skincolor) : ?>
	<tr>
	<td class="center"><?php print $skincolor->id; ?></td>
	<td class="hidden-xs"><?php echo $this->escapeHtml($skincolor->name);?></td>
	<td class="hidden-xs"><?php print ($skincolor->active == 1) ? '<span class="label label-sm label-success">Active</span>' : '<span class="label label-sm label-danger">Expired</span>'; ?>
	
	</td>
	
	<td class="hidden-xs"><a href="<?php echo $this->basePath(); ?>/admin/skincolor/update/<?php print $skincolor->id; ?>" class="btn btn-xs btn-green tooltips" data-placement="top" data-original-title="View"><i class="fa fa-share"></i></a></td>

	</tr>
	<?php endforeach; ?>
	</tbody>
	</table>
	</div>
	</div>





	</div></div>











 
 
 
 
 


 
 
 
 
 
 
 
 
 
 
 
