<?php
// module/Album/view/album/album/index.phtml:

$title = 'News Details';
$this->headTitle($title);
?>

<div class="page-header">
	<h1><?php print $this->escapeHtml($row->name); ?> <small>News page</small></h1>
</div>

<?php if($row->external_url) :  ?>
	<p class="text-muted">
	<h4>External Link:</h4>
	<?php print $this->escapeHtml($row->external_url); ?>
	</p>
<?php endif; ?>


<?php if($row->field_image) :  ?>
<p>
<h4>Attached Image:</h4>
<img alt="" src="<?php print $this->basePath();?>/upload/thumb/<?php print $row->field_image; ?>">
</p>
<?php endif; ?>


<?php if($row->created_on) :  ?>
	<p class="text-danger">
	Created On : <code><?php print $row->created_on;?></code>
	</p>
<?php endif; ?>