<?php
// module/Album/view/album/album/index.phtml:

$title = 'Attribute set List';
$this->headTitle($title);
?><?php //echo $this->escapeHtml($title); ?>

<div class="page-header">
<h1>Attribute Set <small>common form elements and layouts</small></h1> 
</div>		
		
		
<p>
<a href="<?php print $this->basePath();?>/admin/attributeset/add" class="btn btn-primary"><i class="fa fa-plus"></i> Add Attribute Set</a>	
</p>		
		
		
		
	<div class="row">
	<div class="col-md-12">
	<div class="panel panel-default">
	<div class="panel-heading">
	<i class="fa fa-external-link-square"></i>
	<span style="padding-left:25px;">Attribute set List</span>
	<div class="panel-tools">
	<a class="btn btn-xs btn-link panel-collapse collapses" href="#">
	</a>
	<a class="btn btn-xs btn-link panel-config" href="#panel-config" data-toggle="modal">
	<i class="fa fa-wrench"></i>
	</a>
	<a class="btn btn-xs btn-link panel-refresh" href="#">
	<i class="fa fa-refresh"></i>
	</a>
	<a class="btn btn-xs btn-link panel-expand" href="#">
	<i class="fa fa-resize-full"></i>
	</a>
	<a class="btn btn-xs btn-link panel-close" href="#">
	<i class="fa fa-times"></i>
	</a>
	</div>
	</div>
	<div class="panel-body">
	
	
	<table class="table table-hover" id="sample-table-1">		
	<thead>
	<tr>
	<th class="center">#</th>
	<th>Name</th>
	<th>Type</th>
	<th class="hidden-xs">Status</th>
	<th></th>
	</tr>
	</thead>
	<tbody>
	<?php 
	foreach($attributesets as $attributeset) { 
	$gettype = $attributeset->attribute_type ;
	switch($gettype)
	{	
			case '1':
					$type = 'Assets';
					break;
			case '2':
					$type = 'Consumables';
					break;
			case '3':
					$type = 'Clothing';
					break;
			default:
					$type = 'Not Defined';
					
	}
	
	?>
	<tr>
	<td class="center"><?php print $attributeset->id; ?></td>
	<td class="hidden-xs"><?php echo $this->escapeHtml($attributeset->name);?></td>
	<td class="hidden-xs"><?php echo $this->escapeHtml($type);?></td>
	<td class="hidden-xs" id="changeStatus<?php print $attributeset->id;?>"><?php print ($attributeset->active == 1) ? '<span id="'.$attributeset->id.'" class="label label-sm label-success change_status" onClick=clickMe(this,\'deactive\')>Active</span>' : '<span id="'.$attributeset->id.'" class="label label-sm label-danger change_status" onClick=clickMe(this,\'active\')>Expired</span>'; ?>
	
	</td>
	
	<td class="hidden-xs"><a href="<?php print $this->basePath();?>/admin/attributefield/add?id=<?php print $attributeset->id; ?>" class="btn btn-primary">
	<i class="fa fa-plus"></i>Add Attribute Field</a></td>											

	</tr>
	<?php }  ?>
	</tbody>
	</table>
	</div>
	</div>





	</div></div>

 
 
 
 
 


 
 
 
 
 
 
 
 
 
 
 
