<?php
//$bankDetails = $this->bank;
$title = 'Add  Deer Size Value';
$this->headTitle($title);
?>
<?php if(count($flashMessages)) : ?>
			<div class="row">
			<div class="col-md-12">
					<div class="alert alert-success">
					<button class="close" data-dismiss="alert">
					×
					</button>
					<i class="fa fa-check-circle"></i>
					<?php foreach ($flashMessages as $msg) : ?>
					 <?php echo $msg; ?>
					<?php endforeach; ?>
					</div>
			</div>
			</div>
<?php endif; ?>	




<div class="row">
<div class="col-md-2"></div>
<div class="col-md-8">
	<!-- start: FORM VALIDATION 1 PANEL -->
	<div class="panel panel-default">
		<div class="panel-heading"> <b>Add Deer Size Value</b> </div>
	
		<div class="panel-body">
			<?php
			$form = $this->form;
			$form->setAttribute('action', $this->url('deer-size', array('action' => 'add')));
			$form->prepare();
			echo $this->form()->openTag($form);
			echo $this->formHidden($form->get('id'));
			?>
			<fieldset>
			
			<div class="form-group">
			<?php print $this->formRow($form->get('name'));?>
			</div>
			<div class="form-group">
			<?php print $this->formRow($form->get('type'));?>
			</div>
			

			<div class="form-group">
			<?php print $this->formRow($form->get('active'));?>
			</div>
			
			<div class="form-actions" align="center">
			<?php print $this->formRow($form->get('submit'));?>
			</div>
			</fieldset>
			
		<?php echo $this->form()->closeTag(); ?>
		</div>
</div>
</div>
<div class="col-md-2"></div>
</div>
