<?php
// module/Album/view/album/album/index.phtml:

$title = 'Attribute set List';
$this->headTitle($title);
?><?php //echo $this->escapeHtml($title); ?>
<p><a href="/admin/tournamentmission/add" class="btn btn-primary"><i class="fa fa-plus"></i>
	 Add New Attribute Field</a></p>
	<div class="row">
	<div class="col-md-12">
	<div class="panel panel-default">
	<div class="panel-heading">
	<i class="fa fa-external-link-square"></i>
	<span style="padding-left:25px;">Attribute Field List</span>
	<div class="panel-tools">
	<a class="btn btn-xs btn-link panel-collapse collapses" href="#">
	</a>
	<a class="btn btn-xs btn-link panel-config" href="#panel-config" data-toggle="modal">
	<i class="fa fa-wrench"></i>
	</a>
	<a class="btn btn-xs btn-link panel-refresh" href="#">
	<i class="fa fa-refresh"></i>
	</a>
	<a class="btn btn-xs btn-link panel-expand" href="#">
	<i class="fa fa-resize-full"></i>
	</a>
	<a class="btn btn-xs btn-link panel-close" href="#">
	<i class="fa fa-times"></i>
	</a>
	</div>
	</div>
	<div class="panel-body">
	<table class="table table-hover" id="sample-table-1">		
	<thead>
	<tr>
	<th class="center">#</th>
	<th>Tournamentmission Name</th>
	<th>Start Date</th>
	<th>End Date</th>
	<th>Tournamentmission Type</th>
	<th class="hidden-xs">Status</th>
	
	</tr>
	</thead>
	<tbody>
	<?php foreach($tournamentmissions as $tournamentmission) : ?>
	<tr>
	<td class="center"><?php print $tournamentmission['id']; ?></td>
	<td class="hidden-xs"><?php echo $this->escapeHtml($tournamentmission['name']);?></td>
	<td class="hidden-xs"><?php echo $this->escapeHtml(date("Y-m-d h:i",$tournamentmission['startDate']));?></td>
	<td class="hidden-xs"><?php echo $this->escapeHtml(date("Y-m-d h:i",$tournamentmission['endDate']));?></td>
	<td class="hidden-xs"><?php echo $this->escapeHtml($tournamentmission['tournamentmissionType']);?></td>
	<td class="hidden-xs" id="changeStatus<?php print $tournamentmission['id'];?>"><?php print ($tournamentmission['active'] == 1) ? '<span id="'.$tournamentmission['id'].'" class="label label-sm label-success change_status" onClick=clickMe(this,\'deactive\')>Active</span>' : '<span id="'.$tournamentmission->id.'" class="label label-sm label-danger change_status" onClick=clickMe(this,\'active\')>Expired</span>'; ?>
	<span class="label label-sm label-success change_status"><a href="/admin/tournamentmission/edit?id=<?php print $tournamentmission['id'];?>">Edit</a></span>
	</td>
	
	
	</tr>
	<?php endforeach; ?>
	</tbody>
	</table>
	</div>
	</div>





	</div></div>











 
 
 
 
 


 
 
 
 
 
 
 
 
 
 
 
