<div class="footer_area">
<div class="container">
<div class="content_section">
<div class="row">
<div class="col-md-6 col-sm-6 social_icon fleft"> 
Follow Us &nbsp;&nbsp; <a href="#"><img src="<?php print $this->basePath();?>/frontend/images/footer_f.png" ></a>&nbsp; 
<a href="#"><img src="<?php print $this->basePath();?>/frontend/images/footer_t.png" ></a> 
<!--<a href="#"><img src="images/footer_mail.png" ></a>--> 
</div>
	<div class="col-md-6 col-sm-6 footer_download_align social_icon fright"> 
	Download "Game Title" &nbsp;&nbsp;<a href="https://itunes.apple.com/us/app/bow-hunter-2015/id992020597?ls=1&mt=8"><img src="<?php print $this->basePath();?>/frontend/images/footer_mac.png" ></a>&nbsp; 
	<a href="#"><img src="<?php print $this->basePath();?>/frontend/images/footer_and.png" ></a> 
	</div>
</div>
</div>
</div>
</div>
			<div class="footer_area_dn">
			<div class="container">
			<div class="content_section">
			<div class="row">
			<div class="col-md-5 col-sm-4">
			<div class="copy_section">Copyright &copy; 2015 "Company Name". All Rights Reserved.</div>
			</div>
			<div class="col-md-7 col-sm-8">
			<ul class="footer_menu">
			<li><a href="<?php print $this->basePath();?>/application/index/subscribe">Sign Up</a></li>
			<li><a href="<?php print $this->basePath();?>/application/page/index/how-to-play">How to play</a></li>
			<li><a href="http://matrixmedia.redappletech.com/huntinggame/public/application/index#screenshots">Screenshots</a></li>
			<li><a href="http://matrixmedia.redappletech.com/huntinggame/public/application/index#video">Video</a></li>
			<li><a href="<?php print $this->basePath();?>/application/index/customer-support">Customer support</a></li>
			<li><a href="<?php print $this->basePath();?>/application/page/index/privacy-policy">Privacy policy</a></li>
			<li><a href="<?php print $this->basePath();?>/application/page/index/help">Help</a></li>
			</ul>
			</div>
			</div>
			</div>
			</div>
			</div>












		 <script>
			//jQuery(document).ready(function() {
				//Main.init();
			//});
		</script>