<a class="sidebar_section" href="<?php print $this->basePath();?>/application/page/index/recent-offers"<?php if($this->active_menu == 'recent-offers' ) : ?> <?php endif;?> >
<div class="btn_icon"> <img src="<?php print $this->basePath();?>/frontend/images/recent_offers_icon.png" > </div>
<div class="btn_icon_content"> recent <span>offers</span> </div>
</a> 

<!--
<a class="sidebar_section">
<div class="btn_icon"> <img src="<?php print $this->basePath();?>/frontend/images/turnaments_icon.png" > </div>
<div class="btn_icon_content"><span>Tournaments</span></div>
</a> 
-->


<div class="sidebar_sectiontournament" >
                    <a class="sidebar_section" href="<?php print $this->basePath();?>/application/page/index/tournaments-bowhunter"<?php if($this->active_menu == 'tournaments-bowhunter' ) : ?>  <?php endif;?>> 
                    <div class="btn_icon"> <img src="<?php print $this->basePath();?>/frontend/images/turnaments_icon.png"> </div>
                    <div class="btn_icon_content"><span>Tournaments</span></div>
                    
                    </a>

</div>
<a class="sidebar_section" href="<?php print $this->basePath();?>/application/page/index/news-bowhunter"<?php if($this->active_menu == 'news-bowhunter' ) : ?> <?php endif;?>> 
<div class="btn_icon_content">Latest <span>News</span> </div>
</a> 

<a class="sidebar_section" href="<?php print $this->basePath();?>/application/page/index/marketing-partners"<?php if($this->active_menu == 'marketing-partners' ) : ?> <?php endif;?>>
<div class="btn_icon_content"><span>Sponsors</span></div>
</a> 

<a class="sidebar_section" href="<?php print $this->basePath();?>/application/page/index/vedio-ineterview"<?php if($this->active_menu == 'vedio-ineterview' ) : ?> <?php endif;?>>
<div class="btn_icon1"> <img src="<?php print $this->basePath();?>/frontend/images/interview_man.png" > </div>
<div class="btn_icon_content"> Video <br/>
<span>Interview</span> </div>
</a> 

<a href="<?php print $this->basePath();?>/application/page/index/development-team" class="sidebar_section"> 
<div class="btn_icon_content"> <span>Development</span> <br/>
Team </div>
</a> 
<?php //$this->layout()->nav?>