<div class="leader_board_area">
<img src="<?php print $this->basePath();?>/frontend/images/leaderboard_inactive.jpg" border="0" >
</div>


<div class="leader_board_area" style="display:none">

<div class="leader_board_txt"> <img src="<?php print $this->basePath();?>/frontend/images/tournment_icon.png" alt=""> Tournament<br>
<span>Leaderboard</span> <?php print $this->layout()->myVariable ; ?></div>
<div class="panel-group" id="accordion"> 

<!-- 1 -->

<div class="panel panel-default">
<div class="panel-heading  bg1">
<h4 class="panel-title"> <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion" href="#collapseOne"> Daily Leaderboard <i class="indicator glyphicon glyphicon-minus  pull-right"></i> </a> </h4>
</div>
<div id="collapseOne" class="panel-collapse collapse in">
<div class="panel-body"> 
<!-- scroll -->
<div class="scroll_pan">
<ol>
<li><img src="<?php print $this->basePath();?>/frontend/images/daily_01.jpg" alt=""> <img src="<?php print $this->basePath();?>/frontend/images/daily_02.jpg" alt="">grand master <span>100000</span></li>
<li><img src="<?php print $this->basePath();?>/frontend/images/daily_01.jpg" alt=""> <img src="<?php print $this->basePath();?>/frontend/images/daily_02.jpg" alt="">grand master <span>100000</span></li>
<li><img src="<?php print $this->basePath();?>/frontend/images/daily_01.jpg" alt=""> <img src="<?php print $this->basePath();?>/frontend/images/daily_02.jpg" alt="">grand master <span>100000</span></li>
<li><img src="<?php print $this->basePath();?>/frontend/images/daily_01.jpg" alt=""> <img src="<?php print $this->basePath();?>/frontend/images/daily_02.jpg" alt="">grand master <span>100000</span></li>
<li><img src="<?php print $this->basePath();?>/frontend/images/daily_01.jpg" alt=""> <img src="<?php print $this->basePath();?>/frontend/images/daily_02.jpg" alt="">grand master <span>100000</span></li>
<li><img src="<?php print $this->basePath();?>/frontend/images/daily_01.jpg" alt=""> <img src="<?php print $this->basePath();?>/frontend/images/daily_02.jpg" alt="">grand master <span>100000</span></li>
<li><img src="<?php print $this->basePath();?>/frontend/images/daily_01.jpg" alt=""> <img src="<?php print $this->basePath();?>/frontend/images/daily_02.jpg" alt="">grand master <span>100000</span></li>
<li><img src="<?php print $this->basePath();?>/frontend/images/daily_01.jpg" alt=""> <img src="<?php print $this->basePath();?>/frontend/images/daily_02.jpg" alt="">grand master <span>100000</span></li>
<li><img src="<?php print $this->basePath();?>/frontend/images/daily_01.jpg" alt=""> <img src="<?php print $this->basePath();?>/frontend/images/daily_02.jpg" alt="">grand master <span>100000</span></li>
<li><img src="<?php print $this->basePath();?>/frontend/images/daily_01.jpg" alt=""> <img src="<?php print $this->basePath();?>/frontend/images/daily_02.jpg" alt="">grand master <span>100000</span></li>
<li><img src="<?php print $this->basePath();?>/frontend/images/daily_01.jpg" alt=""> <img src="<?php print $this->basePath();?>/frontend/images/daily_02.jpg" alt="">grand master <span>100000</span></li>
<li><img src="<?php print $this->basePath();?>/frontend/images/daily_01.jpg" alt=""> <img src="<?php print $this->basePath();?>/frontend/images/daily_02.jpg" alt="">grand master <span>100000</span></li>
<li><img src="<?php print $this->basePath();?>/frontend/images/daily_01.jpg" alt=""> <img src="<?php print $this->basePath();?>/frontend/images/daily_02.jpg" alt="">grand master <span>100000</span></li>
<li><img src="<?php print $this->basePath();?>/frontend/images/daily_01.jpg" alt=""> <img src="<?php print $this->basePath();?>/frontend/images/daily_02.jpg" alt="">grand master <span>100000</span></li>
<li><img src="<?php print $this->basePath();?>/frontend/images/daily_01.jpg" alt=""> <img src="<?php print $this->basePath();?>/frontend/images/daily_02.jpg" alt="">grand master <span>100000</span></li>
<li><img src="<?php print $this->basePath();?>/frontend/images/daily_01.jpg" alt=""> <img src="<?php print $this->basePath();?>/frontend/images/daily_02.jpg" alt="">grand master <span>100000</span></li>









</ol>
<div class="clearDiv"></div>
</div>
</div>
</div>
</div>

<!-- 2 -->

<div class="panel panel-default">
<div class="panel-heading bg2">
<h4 class="panel-title"> <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion" href="#collapseTwo"> Weekly Leaderboard <i class="indicator glyphicon glyphicon-plus  pull-right"></i> </a> </h4>
</div>
<div id="collapseTwo" class="panel-collapse collapse">
<div class="panel-body"> 
<!-- scroll -->
<div class="scroll_pan">
<ol>
<li><img src="<?php print $this->basePath();?>/frontend/images/daily_01.jpg" alt=""> <img src="<?php print $this->basePath();?>/frontend/images/daily_02.jpg" alt="">grand master <span>100000</span></li>
<li><img src="<?php print $this->basePath();?>/frontend/images/daily_01.jpg" alt=""> <img src="<?php print $this->basePath();?>/frontend/images/daily_02.jpg" alt="">grand master <span>100000</span></li>
<li><img src="<?php print $this->basePath();?>/frontend/images/daily_01.jpg" alt=""> <img src="<?php print $this->basePath();?>/frontend/images/daily_02.jpg" alt="">grand master <span>100000</span></li>

</ol>
<div class="clearDiv"></div>
</div>
</div>
</div>
</div>

<!-- 3 -->

<div class="panel panel-default">
<div class="panel-heading  bg1">
<h4 class="panel-title"> <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion" href="#collapseThree"> Monthly Leaderboard <i class="indicator glyphicon glyphicon-plus pull-right"></i> </a> </h4>
</div>
<div id="collapseThree" class="panel-collapse collapse">
<div class="panel-body"> 
<!-- scroll -->
<div class="scroll_pan">
<ol>
<li><img src="<?php print $this->basePath();?>/frontend/images/daily_01.jpg" alt=""> <img src="<?php print $this->basePath();?>/frontend/images/daily_02.jpg" alt="">grand master <span>100000</span></li>
<li><img src="<?php print $this->basePath();?>/frontend/images/daily_01.jpg" alt=""> <img src="<?php print $this->basePath();?>/frontend/images/daily_02.jpg" alt="">grand master <span>100000</span></li>
<li><img src="<?php print $this->basePath();?>/frontend/images/daily_01.jpg" alt=""> <img src="<?php print $this->basePath();?>/frontend/images/daily_02.jpg" alt="">grand master <span>100000</span></li>
<li><img src="<?php print $this->basePath();?>/frontend/images/daily_01.jpg" alt=""> <img src="<?php print $this->basePath();?>/frontend/images/daily_02.jpg" alt="">grand master <span>100000</span></li>

</ol>
<div style="clear:both;height:5px;"></div>
</div>
</div>
</div>
</div>

<!----> 

</div>
</div>

<!-- add area -->
            <div> <a href="#"><img src="<?php print $this->basePath();?>/frontend/images/pizza_img.jpg" ></a> </div>