<?php /* ?>
<a href="<?php print $this->basePath();?>/application/index/tournaments" class="sidebar_section active">
<div class="btn_icon_content">Daily<br />	
<span>Tournaments</span>
</div>
</a>

<a href="<?php print $this->basePath();?>/application/index/tournaments?type=weekly" class="sidebar_section">
<div class="btn_icon_content">Weekly<br />
<span>Tournaments</span>
</div>
</a>                                    


<a href="<?php print $this->basePath();?>/application/index/tournaments?type=monthly" class="sidebar_section">
<div class="btn_icon_content">Monthly<br />
<span>Tournaments</span>
</div>
</a>

<!-- leader board -->
<div class="leader_board_area">
<a href="#"><img src="<?php print $this->basePath();?>/frontend/images/pizza_offers.jpg" border="0" ></a>
</div>
<!-- add area -->
<div> <a href="#"><img src="<?php print $this->basePath();?>/frontend/images/pizza_img.jpg" ></a></div>
	
<?php */ ?>


<a  class="sidebar_section active">
<div class="btn_icon_content">Daily<br />	
<span>Tournaments</span>
</div>
</a>

<a  class="sidebar_section">
<div class="btn_icon_content">Weekly<br />
<span>Tournaments</span>
</div>
</a>                                    


<a class="sidebar_section">
<div class="btn_icon_content">Monthly<br />
<span>Tournaments</span>
</div>
</a>

<!-- leader board -->
<div class="leader_board_area">
<a href="#"><img src="<?php print $this->basePath();?>/frontend/images/pizza_offers.jpg" border="0" ></a>
</div>
<!-- add area -->
<div> <a href="#"><img src="<?php print $this->basePath();?>/frontend/images/pizza_img.jpg" ></a></div>