<?php
//$bankDetails = $this->bank;
$title = 'Add Player Position Value';
$this->headTitle($title);
?>
<div class="page-header">
<h1>News <small> common form elements and layouts</small></h1>

</div>



<?php if(count($flashMessages)) : ?>
			<div class="row">
			<div class="col-md-12">
					<div class="alert alert-success">
					<button class="close" data-dismiss="alert">
					×
					</button>
					<i class="fa fa-check-circle"></i>
					<?php foreach ($flashMessages as $msg) : ?>
					 <?php echo $msg; ?>
					<?php endforeach; ?>
					</div>
			</div>
			</div>
<?php endif; ?>	




<div class="row">
<div class="col-md-2"></div>
<div class="col-md-8">
	<!-- start: FORM VALIDATION 1 PANEL -->
	<div class="panel panel-default">
		<div class="panel-heading"><i class="fa fa-external-link-square"></i> <b>Add Recent News</b> </div>
	
		<div class="panel-body">
			<?php
			$form = $this->form;
			$form->setAttribute('action', $this->url('news', array('action' => 'add')));
			$form->prepare();
			echo $this->form()->openTag($form);
			echo $this->formHidden($form->get('id'));
			?>
			<fieldset>
			
			<div class="form-group">
			<?php print $this->formRow($form->get('title'));?>
			</div>
	
			<div class="form-group">
			<?php print $this->formRow($form->get('external_url'));?>
			</div>

								
			<div class="form-group">
			<label class="control-label">
			Detail Description :
			</label>
			<?php print $this->formRow($form->get('news_content'));?>
			</div>


			<div class="form-group">
			<?php print $this->formRow($form->get('active'));?>
			</div>
			
			<div class="form-actions" align="right">
			<?php print $this->formRow($form->get('submit'));?>
			</div>
			</fieldset>
			
		<?php echo $this->form()->closeTag(); ?>
		</div>
</div>
</div>
<div class="col-md-2"></div>
</div>
