<?php
$getRow= $this->getData;
$title = $getRow->title ; 
$this->headTitle($title);
?>
<div class="page-header">
<h1>Edit News Details <small>common form elements and layouts</small></h1>
</div>


<div class="row">
<div class="col-md-2"></div>
<div class="col-md-8">
	<!-- start: FORM VALIDATION 1 PANEL -->
	<div class="panel panel-default">
		<div class="panel-heading"> <b>Edit  -  <?php print $title; ?> </b> </div>
	
		<div class="panel-body">
			<?php
			$form = $this->form;
			$form->setAttribute('action', $this->url('news', array('action' => 'edit' ,  'id' => $id)));
			$form->prepare();
			echo $this->form()->openTag($form);
			echo $this->formHidden($form->get('id'));
			?>
			<fieldset>
			
			<div class="form-group">
			<?php print $this->formRow($form->get('title'));?>
			</div>
	
			<div class="form-group">
			<?php print $this->formRow($form->get('external_url'));?>
			</div>

								
			<div class="form-group">
			<label class="control-label">
			News Details :
			</label>
			<?php print $this->formRow($form->get('news_content'));?>
			</div>

			<div class="form-group">
			<?php print $this->formRow($form->get('active'));?>
			</div>			

			<div class="form-actions" align="center">
			<?php print $this->formRow($form->get('submit'));?>
			</div>
			</fieldset>
			
		<?php echo $this->form()->closeTag(); ?>
		</div>
</div>
</div>
<div class="col-md-2"></div>
</div>
