<?php
$title = 'Add New Tournament';
$this->headTitle($title);
?>

<div class="page-header">
<h1><i class="fa fa-plus"></i> Add New Tournament <small>common form for adding tournament</small></h1>


</div>








<div class="row">

<div class="col-sm-12">
	<!-- start: FORM VALIDATION 1 PANEL -->
<div class="panel panel-default">
<div class="panel-heading"> <b>Add Tournament</b> </div>	
<div class="panel-body">

						<?php
						$form = $this->form;
						$form->setAttribute('action', $this->url('tournament', array('action' => 'add')));
						$form->prepare();
						echo $this->form()->openTag($form); 
						?>
					
						<div class="form-group">										
						<label for="form-field-select-1">Tournament Name</label>
						<?php print $this->formRow($form->get('name'));?>
						</div>
						
						<div class="form-group">										
						<label for="form-field-select-1">Tournament Duration (In Days)</label>
						<?php print $this->formRow($form->get('duration'));?>
						</div>						

						
						<div class="form-group">
						<label for="form-field-select-1">Select Start Date</label>	<span class="glyphicon glyphicon-calendar"></span>					
						<?php print $this->formRow($form->get('start_date'));?>						
						</div>
						
						<div class="form-group">
						<label for="form-field-select-1">Select End Date</label>	<span class="glyphicon glyphicon-calendar"></span>	
						<?php print $this->formRow($form->get('end_date'));?>						
						</div>

						<div class="form-group">
						<label for="form-field-select-1">Tournament Type</label>								
						<?php print $this->formRow($form->get('tournament_type'));?>
						</div>						

						<div class="form-group">
						<label for="form-field-select-1">Minimum Entry Points</label>								
						<?php print $this->formRow($form->get('entry_points'));?>
						</div>
						
						<div class="form-group">														
						<div class="col-sm-12" align="right"><?php //print $this->formRow($form->get('number_0f_missions'));?></div>										
						</div>

						<div class="form-actions" align="right">						
						<div class="col-sm-12"><?php print $this->formRow($form->get('submit'));?></div>		
						</div>
					
					

<?php 
//echo $this->formCollection($form);
echo $this->form()->closeTag();
?>
</div>
</div>
</div>

</div>


		

