<?php
// module/Album/view/album/album/index.phtml:

$title = 'Tournament List';
$this->headTitle($title);
?><?php //echo $this->escapeHtml($title); ?>

<div class="page-header">
<h1><a href="<?php print $this->basePath(); ?>/admin/tournament/add" class="btn btn-primary"><i class="fa fa-plus"></i> Add New Tournament</a> 
<small>common form for adding tournament</small></h1>

</div>	 
	 
	 
	 
	 
	 
	 
<?php if(count($flashMessages)) : ?>
			<div class="row">
			<div class="col-md-12">
					<div class="alert alert-success">
					<button class="close" data-dismiss="alert">
					×
					</button>
					<i class="fa fa-check-circle"></i>
					<?php foreach ($flashMessages as $msg) : ?>
					<strong>Well done!</strong> <?php echo $msg; ?>
					<?php endforeach; ?>
					</div>
			</div>
			</div>
<?php endif; ?>	 
	 
	 
	 
	 
	 
	 
	<div class="row">
	<div class="col-md-12">
	<div class="panel panel-default">
	<div class="panel-heading">
	<i class="fa fa-external-link-square"></i>
	<span style="padding-left:25px;">Tournament Lists</span>
	<div class="panel-tools">
	<a class="btn btn-xs btn-link panel-collapse collapses" href="#">
	</a>
	<a class="btn btn-xs btn-link panel-config" href="#panel-config" data-toggle="modal">
	<i class="fa fa-wrench"></i>
	</a>
	<a class="btn btn-xs btn-link panel-refresh" href="#">
	<i class="fa fa-refresh"></i>
	</a>
	<a class="btn btn-xs btn-link panel-expand" href="#">
	<i class="fa fa-resize-full"></i>
	</a>
	<a class="btn btn-xs btn-link panel-close" href="#">
	<i class="fa fa-times"></i>
	</a>
	</div>
	</div>
	<div class="panel-body">
	<table class="table table-hover" id="sample-table-1">		
	<thead>
	<tr>
	<th class="center">#</th>
	<th>Tournament Name</th>
	<th>Duration(Days)</th>
	<th>Start Date</th>
	<th>End Date</th>
	<th>Tournament Type</th>
	<th>Entry Points</th>
	<th class="hidden-xs">Status</th>
	<th class="hidden-xs"></th>
	<th class="hidden-xs"></th>
	</tr>
	</thead>
	<tbody>
	<?php foreach($tournaments as $tournament) : ?>
	<tr>
	<td class="center"><?php print $tournament['id']; ?></td>
	<td class="hidden-xs"><a href="<?php print $this->basePath(); ?>/admin/missions/index/<?php print $tournament['id']; ?>"><?php echo $this->escapeHtml($tournament['name']);?></a></td>
	<td class="hidden-xs"><?php echo $this->escapeHtml($tournament['duration']);?></td>
	<td class="hidden-xs"><?php echo $this->escapeHtml(date("Y-m-d h:i",$tournament['start_date']));?></td>
	<td class="hidden-xs"><?php echo $this->escapeHtml(date("Y-m-d h:i",$tournament['end_date']));?></td>
	<td class="hidden-xs"><?php echo $this->escapeHtml($tournament['tournament_type']);?></td>
	<td class="hidden-xs"><?php echo $this->escapeHtml($tournament['entry_points']);?></td>
	<td class="hidden-xs" id="changeStatus<?php print $tournament['id'];?>"><?php print ($tournament['active'] == 1) ? '<span id="'.$tournament['id'].'" class="label label-sm label-success change_status" >Active</span>' : '<span id="'.$tournament->id.'" class="label label-sm label-danger change_status" >Expired</span>'; ?>
	
	</td>
	<td class="hidden-xs">
		<a href="<?php print $this->basePath(); ?>/admin/missions/add/<?php print $tournament['id']; ?>" class="btn btn-primary btn-xs"><i class="fa fa-plus"></i>Add Mission</a>
		</td>
		<td class="center">
	
	
	<div class="visible-md visible-lg hidden-sm hidden-xs">
	<a href="<?php print $this->basePath(); ?>/admin/tournament/edit/<?php print $tournament['id']; ?>" class="btn btn-xs btn-teal tooltips" data-placement="top" data-original-title="Edit"><i class="fa fa-edit"></i></a>
	
	<a href="<?php print $this->basePath(); ?>/admin/tournament/delete/<?php print $tournament['id']; ?>" class="btn btn-xs btn-bricky tooltips" data-placement="top" data-original-title="Remove"><i class="fa fa-times fa fa-white"></i></a>
	</div>
	<div class="visible-xs visible-sm hidden-md hidden-lg">
	<div class="btn-group">
	<a class="btn btn-primary dropdown-toggle btn-sm" data-toggle="dropdown" href="#">
	<i class="fa fa-cog"></i> <span class="caret"></span>
	</a>
	<ul role="menu" class="dropdown-menu pull-right">
	
	<li role="presentation">
	<a role="menuitem" tabindex="-1" href="<?php print $this->basePath(); ?>/admin/tournament/edit/<?php print $tournament['id']; ?>">
	<i class="fa fa-edit"></i> Edit
	</a>
	</li>

	<li role="presentation">
	<a role="menuitem" tabindex="-1" href="<?php print $this->basePath(); ?>/admin/tournament/delete/<?php print $tournament['id']; ?>">
	<i class="fa fa-times"></i> Remove
	</a>
	</li>
	</ul>
	</div>
	</div>
	
	
	
	
	
	
	
	</td>
	
	
	
	
	
	
	</tr>
	<?php endforeach; ?>
	</tbody>
	</table>
	</div>
	</div>





	</div></div>











 
 
 
 
 


 
 
 
 
 
 
 
 
 
 
 
