<?php
$bankDetails = $this->bank;
$title = 'Add Purchase Items';
$this->headTitle($title);
?>

<div class="row">
<div class="col-md-2"></div>
<div class="col-md-8">
	<!-- start: FORM VALIDATION 1 PANEL -->
	<div class="panel panel-default">
		<div class="panel-heading"> <b>Add New Deer Information</b> </div>
	
		<div class="panel-body">
			<?php
			$form = $this->form;
			$form->setAttribute('action', $this->url('deerinfo', array('action' => 'add')));
			$form->prepare();
			echo $this->form()->openTag($form);
			echo $this->formHidden($form->get('id'));
			?>
			<fieldset>
			
			<div class="form-group">
			<label for="form-field-select-1">Deer Activity</label>																					
			<?php print $this->formRow($form->get('deer_activity_id'));?>
			</div>
			
			<div class="form-group">
			<label for="form-field-select-1">Deer Size</label>																					
			<?php print $this->formRow($form->get('deer_size_id'));?>
			</div>			
			
			<div class="form-group">
			<label for="form-field-select-1">Deer Facing</label>																					
			<?php print $this->formRow($form->get('deer_facing_id'));?>
			</div>			
			
			<div class="form-group">
			<label for="form-field-select-1">Deer Position</label>																					
			<?php print $this->formRow($form->get('deer_position_id'));?>
			</div>			
			
			
			

			<div class="form-group">
			<?php print $this->formRow($form->get('min_start_range'));?>
			</div>
			
			
			
			
			<div class="form-group">
			<?php print $this->formRow($form->get('max_start_range'));?>
			</div>
			
			<div class="form-group">
			<label for="form-field-select-1">Kill For Success</label>																					
			<?php print $this->formRow($form->get('kill_for_success'));?>
			</div>	
			
			
			
			
			
			
			

			<div class="form-group">
			<?php print $this->formRow($form->get('active'));?>
			</div>
			
			<div class="form-actions" align="center">
			<?php print $this->formRow($form->get('submit'));?>
			</div>
			</fieldset>
			
		<?php echo $this->form()->closeTag(); ?>
		</div>
</div>
</div>
<div class="col-md-2"></div>
</div>
