<?php
// module/Album/view/album/album/index.phtml:

$title = 'Deer Information';
$this->headTitle($title);

?>
<?php //echo $this->escapeHtml($title); ?>
<p><a href="<?php print $this->basePath(); ?>/admin/deerinfo/add" class="btn btn-primary"><i class="fa fa-plus"></i>Add New </a></p>

<?php if(count($flashMessages)) : ?>
			<div class="row">
			<div class="col-md-12">
					<div class="alert alert-success">
					<button class="close" data-dismiss="alert">
					×
					</button>
					<i class="fa fa-check-circle"></i>
					<?php foreach ($flashMessages as $msg) : ?>
					<strong>Well done!</strong> <?php echo $msg; ?>
					<?php endforeach; ?>
					</div>
			</div>
			</div>
<?php endif; ?>





	 

	<div class="row">
	<div class="col-md-12">
	<div class="panel panel-default">
	<div class="panel-heading">
	<i class="fa fa-external-link-square"></i>
	<span style="padding-left:25px;">Deer Information</span>
	<div class="panel-tools">
	<a class="btn btn-xs btn-link panel-collapse collapses" href="#">
	</a>
	<a class="btn btn-xs btn-link panel-config" href="#panel-config" data-toggle="modal">
	<i class="fa fa-wrench"></i>
	</a>
	<a class="btn btn-xs btn-link panel-refresh" href="#">
	<i class="fa fa-refresh"></i>
	</a>
	<a class="btn btn-xs btn-link panel-expand" href="#">
	<i class="fa fa-resize-full"></i>
	</a>
	<a class="btn btn-xs btn-link panel-close" href="#">
	<i class="fa fa-times"></i>
	</a>
	</div>
	</div>
	
	<div class="panel-body">
	<table class="table table-hover" id="sample-table-1">		
	<thead>
	<tr>
	<th class="center">#</th>
	<th>Activity</th>	
	<th>Size</th>
	<th>Facing</th>
	<th>Position</th>
	<th class="hidden-xs">Min Range</th>
	<th class="hidden-xs">Max Range</th>
	<th>Kill for Success</th>
	</tr>
	</thead>
	<tbody>
	<?php foreach($deerinfo as $val) : ?>
	<tr>
	<td class="center"><?php print $val->id; ?></td>
	<td class="hidden-xs"><?php if(array_key_exists($val->deer_activity_id , $this->deerActivityRows) ) print $this->deerActivityRows[$val->deer_activity_id]; ?></td>
	<td class="hidden-xs"><?php if(array_key_exists($val->deer_size_id , $this->deerSizeLists) ) print $this->deerSizeLists[$val->deer_size_id]; ?></td>
	<td class="hidden-xs"><?php if(array_key_exists($val->deer_facing_id , $this->deerFacingLists) ) print $this->deerFacingLists[$val->deer_facing_id]; ?></td>
	<td class="hidden-xs"><?php if(array_key_exists($val->deer_position_id , $this->deerPositionLists) ) print $this->deerPositionLists[$val->deer_position_id]; ?></td>
	<td class="center"><?php print $val->min_start_range ;?></td>								
	<td class="hidden-xs"><?php print $val->max_start_range ;?></td>
	<td class="hidden-xs"><?php print ($val->kill_for_success == 1) ? 'Success' : 'Failure';?></td>
	<td class="center">
	
	
	<div class="visible-md visible-lg hidden-sm hidden-xs">
	<a href="<?php print $this->basePath(); ?>/admin/deerinfo/edit/<?php print $val->id; ?>" class="btn btn-xs btn-teal tooltips" data-placement="top" data-original-title="Edit"><i class="fa fa-edit"></i></a>
	
	<a href="<?php print $this->basePath(); ?>/admin/deerinfo/delete/<?php print $val->id; ?>" class="btn btn-xs btn-bricky tooltips" data-placement="top" data-original-title="Remove"><i class="fa fa-times fa fa-white"></i></a>
	</div>
	<div class="visible-xs visible-sm hidden-md hidden-lg">
	<div class="btn-group">
	<a class="btn btn-primary dropdown-toggle btn-sm" data-toggle="dropdown" href="#">
	<i class="fa fa-cog"></i> <span class="caret"></span>
	</a>
	<ul role="menu" class="dropdown-menu pull-right">
	
	<li role="presentation">
	<a role="menuitem" tabindex="-1" href="<?php print $this->basePath(); ?>/admin/deerinfo/edit/<?php print $val->id; ?>">
	<i class="fa fa-edit"></i> Edit
	</a>
	</li>

	<li role="presentation">
	<a role="menuitem" tabindex="-1" href="<?php print $this->basePath(); ?>/admin/deerinfo/delete/<?php print $val->id; ?>">
	<i class="fa fa-times"></i> Remove
	</a>
	</li>
	</ul>
	</div>
	</div>
	
	
	
	
	
	
	
	</td>

	</tr>
	<?php endforeach; ?>
	</tbody>
	</table>
	</div>
	</div>





	</div></div>




 
 
 
 
 


 
 
 
 
 
 
 
 
 
 
 
