<?php
$title = 'Add New Attribute Set';
$this->headTitle($title);
?>
<!-- <h1><?php //echo $this->escapeHtml($title); ?></h1> -->
<style>
.box-top-space {
margin-top: 5px !important;
}

</style>

<?php
if(!isset($noSetSelected))
{
?>
<div class="page-header">
<p><a href="/huntinggame/public/admin/weapon/index" class="btn btn-light-grey"><i class="fa fa-arrow-circle-left"> Back </i></a></p>
</div>

<div class="row">
<div class="col-md-2"></div>
<div class="col-md-8">
	<!-- start: FORM VALIDATION 1 PANEL -->
	<div class="panel panel-default">
		<div class="panel-heading"> <b>Add Weapon</b> </div>
	
	<div class="panel-body">
	<?php
	$form = $this->form;
	$form->setAttribute('action', $this->url('weapon', array('action' => 'add')));
	$form->prepare();
	echo $this->form()->openTag($form);  ?>
	<fieldset>
		<div class="form-group">
			<?php  echo $this->formCollection($form);?>
		</div>
		
	
	
	<div class="form-actions" align="right">
	<?php echo $this->form()->closeTag(); ?>
	</div>
	</fieldset>	
	
	</div>
</div>
</div>
<div class="col-md-2"></div>
</div>
<?php

} else {
?>
<div class="page-header">
<p><a href="/huntinggame/public/admin/weapon/index" class="btn btn-light-grey"><i class="fa fa-arrow-circle-left"> Back </i></a></p>
</div>

<div class="form-group">
<label for="form-field-select-1">
	Select Weapon Type
</label>
<form name="myFrm" id="myFrm" action="/huntinggame/public/admin/weapon/add">
<select class="form-control" id="form-field-selectsetList">
	<option value="">Select Options</option>
	<?php foreach($attributesetLists as $attributesetList){ ?>
	<option value="<?php echo $attributesetList->id; ?>"><?php echo $attributesetList->name; ?></option>
	<?php } ?>
</select>
<form>
</div> 
 
<?php 
}
?>