<?php
// module/Album/view/album/album/index.phtml:

$title = 'Attribute set List';
$this->headTitle($title);
?><?php //echo $this->escapeHtml($title); ?>
<div class="page-header">
<h1>Add Field Value <small>common form elements and layouts</small></h1> 
</div>


<p>
<a href="<?php echo $this->basePath(); ?>/admin/weapon/add" class="btn btn-primary"><i class="fa fa-plus"></i> Add Field Value</a>	
</p>
	 
	 
	 
	<div class="row">
	<div class="col-md-12">
	<div class="panel panel-default">
	<div class="panel-heading">
	<i class="fa fa-external-link-square"></i>
	<span style="padding-left:25px;">Attribute Field List</span>
	<div class="panel-tools">
	<a class="btn btn-xs btn-link panel-collapse collapses" href="#">
	</a>
	<a class="btn btn-xs btn-link panel-config" href="#panel-config" data-toggle="modal">
	<i class="fa fa-wrench"></i>
	</a>
	<a class="btn btn-xs btn-link panel-refresh" href="#">
	<i class="fa fa-refresh"></i>
	</a>
	<a class="btn btn-xs btn-link panel-expand" href="#">
	<i class="fa fa-resize-full"></i>
	</a>
	<a class="btn btn-xs btn-link panel-close" href="#">
	<i class="fa fa-times"></i>
	</a>
	</div>
	</div>
	<div class="panel-body">
	<table class="table table-hover" id="sample-table-1">		
	<thead>
	<tr>
	<th class="center">#</th>
	<th>Weapon Type</th>
	<th>Name</th>
	<th>Price</th>
	<th class="hidden-xs">Status</th>
	
	</tr>
	</thead>
	<tbody>
	<?php foreach($weapons as $weapon) : ?>
	<tr>
	<td class="center"><?php print $weapon['id']; ?></td>
	<td class="hidden-xs"><?php echo $this->escapeHtml($weapon['setName']);?></td>
	<td class="hidden-xs"><?php echo $this->escapeHtml($weapon['name']);?></td>
	<td class="hidden-xs"><?php echo $this->escapeHtml($weapon['price']);?></td>
	<td class="hidden-xs" id="changeStatus<?php print $weapon['id'];?>"><?php print ($weapon['active'] == 1) ? '<span id="'.$weapon['id'].'" class="label label-sm label-success change_status" onClick=clickMe(this,\'deactive\')>Active</span>' : '<span id="'.$weapon->id.'" class="label label-sm label-danger change_status" onClick=clickMe(this,\'active\')>Expired</span>'; ?>
	
	</td>
	
	</tr>
	<?php endforeach; ?>
	</tbody>
	</table>
	</div>
	</div>





	</div></div>











 
 
 
 
 


 
 
 
 
 
 
 
 
 
 
 
