<?php
// module/Album/view/album/album/index.phtml:

$title = 'Player Lists';
$this->headTitle($title);
?>
<!-- <h1><?php //echo $this->escapeHtml($title); ?></h1> -->
	<div class="row">
	<div class="col-md-12">
	<div class="panel panel-default">
	<div class="panel-heading">
	<i class="fa fa-external-link-square"></i>
	<span style="padding-left:25px;">Player Lists</span>
	<div class="panel-tools">
	<a class="btn btn-xs btn-link panel-collapse collapses" href="#">
	</a>
	<a class="btn btn-xs btn-link panel-config" href="#panel-config" data-toggle="modal">
	<i class="fa fa-wrench"></i>
	</a>
	<a class="btn btn-xs btn-link panel-refresh" href="#">
	<i class="fa fa-refresh"></i>
	</a>
	<a class="btn btn-xs btn-link panel-expand" href="#">
	<i class="fa fa-resize-full"></i>
	</a>
	<a class="btn btn-xs btn-link panel-close" href="#">
	<i class="fa fa-times"></i>
	</a>
	</div>
	</div>
	<div class="panel-body">
	<table class="table table-hover" id="sample-table-1">		
	<thead>
	<tr>
	<th class="center">#</th>
	<th>Name</th>
	<th class="hidden-xs">Creator</th>
	<th>Xp-Points</th>
	<th class="hidden-xs">Energy</th>
	<th class="hidden-xs">Created On</th>
	<th class="hidden-xs">Status</th>
	<th></th>
	</tr>
	</thead>
	<tbody>
	<?php foreach($this->paginator as $player) : ?>
	<tr>
	<td class="center"><?php print $player->id; ?></td>
	<td class="hidden-xs"><a href="<?php echo $this->basePath(); ?>/admin/player/details/<?php print $player->id; ?>" rel="nofollow" target="_blank"><?php echo $this->escapeHtml($player->name);?></a></td>
	<td><?php echo $player->socialType; ?></td>
	<td><?php print $player->xpPoint; ?></td>											
	<td class="hidden-xs"><?php print $player->totalEnergy; ?></td>
	<td class="hidden-xs"><?php print date("m/d/Y" , strtotime($player->createOn)); ?></td>
	<td class="hidden-xs"><?php print ($player->active == 1) ? '<span class="label label-sm label-success">Active</span>' : '<span class="label label-sm label-danger">Expired</span>'; ?>
	
	</td>

	<td class="center">
	<div class="visible-md visible-lg hidden-sm hidden-xs">										
	<a href="<?php echo $this->basePath(); ?>/admin/player/details/<?php print $player->id; ?>" class="btn btn-xs btn-green tooltips" data-placement="top" data-original-title="View"><i class="fa fa-share"></i></a>
	</div>
	<div class="visible-xs visible-sm hidden-md hidden-lg">
	<div class="btn-group">
	<a class="btn btn-primary dropdown-toggle btn-sm" data-toggle="dropdown" href="#">
	<i class="fa fa-cog"></i> <span class="caret"></span>
	</a>
	<ul role="menu" class="dropdown-menu pull-right">
	<li role="presentation">
	<a role="menuitem" tabindex="-1" href="<?php echo $this->basePath(); ?>/admin/player/details/<?php print $player->id; ?>">
	<i class="fa fa-share"></i> View
	</a>
	</li>

	</ul>
	</div>
	</div></td>

	</tr>
	<?php endforeach; ?>
	</tbody>
	</table>
	
	
	</div>
	</div>

	</div></div>

<?php 	echo $this->paginationControl(
    // the paginator object
    $this->paginator,
    // the scrolling style; see http://zf2.readthedocs.org/en/release-2.1.4/modules/zend.paginator.usage.html#rendering-pages-with-view-scripts
    'sliding',
    // the partial to use to render the control
    array('partial/paginator.phtml', 'Player'),
    // the route to link to when a user clicks a control link
    array(
        'route' => 'player'
    )
);	 ?>









 
 
 
 
 


 
 
 
 
 
 
 
 
 
 
 
