<div class="per_content_area">

<h2 class="no_mrg">Customer Support</h2>
<?php if(count($flashMessages)) : ?>
			<div class="row">
					<div class="col-md-12">
							<div class="alert alert-success">
							<button class="close" data-dismiss="alert">
							×
							</button>
							<i class="fa fa-check-circle"></i>
							<?php foreach ($flashMessages as $msg) : ?>
							 <?php echo $msg; ?>
							<?php endforeach; ?>
							</div>
					</div>
			</div>
<?php endif; ?>	









	<?php
	$form = $this->form;
	$form->setAttribute('action', $this->url('index', array('action' => 'customer-support')));
	$form->prepare();
	echo $this->form()->openTag($form);
	echo $this->formHidden($form->get('id'));
	?>
	
	<div class="customer_support">
	
	<div id="error" style="display:none" class="alert alert-danger"> You've got problems. </div>
	<div id="victory" style="display:none" class="alert alert-success"> Victory! </div>	
	
	
	
		<div class="form-group clearfix">
			<div class="col-md-12">
			<!-- <input name="" type="text" placeholder="Your Name" class="form-control"> -->
				<?php print $this->formRow($form->get('name'));?>
				 
			</div>
		</div>
		<div class="col-md-6">
		<div class="form-group clearfix">
			<?php print $this->formRow($form->get('email'));?>
		</div>
		</div>
		<div class="col-md-6">
		<div class="form-group clearfix">
			<?php print $this->formRow($form->get('contactno'));?>
		</div>			
		</div>
		
		<div class="form-group clearfix">
			<div class="col-md-12"><?php print $this->formRow($form->get('subject'));?></div>
		</div>
		
		<div class="form-group clearfix">
			<div class="col-md-12"><?php print $this->formRow($form->get('short_note'));?></div>
		</div>
		
		<div class="form-group clearfix">
			<div class="col-md-12"><?php print $this->formRow($form->get('submit'));?></div>
		</div>
		<div class="clearfix"></div>
	</div>
<?php echo $this->form()->closeTag(); ?>
</div>

		













