	<div class="per_content_area">

	<h2 class="no_mrg">Subscriber Sign up</h2>

<?php if(count($flashMessages)) : ?>
			<div class="row">
					<div class="col-md-12">
							<div class="alert alert-success">
							<button class="close" data-dismiss="alert">
							×
							</button>
							<i class="fa fa-check-circle"></i>
							<?php foreach ($flashMessages as $msg) : ?>
							 <?php echo $msg; ?>
							<?php endforeach; ?>
							</div>
					</div>
			</div>
<?php endif; ?>	
	
<?php if($this->layout()->message) : ?>

		<div class="alert alert-danger">
		<?php foreach ($this->layout()->message as $message) { ?>
		<button class="close" data-dismiss="alert">
		×
		</button>
		<i class="fa fa-times-circle"></i>
		<strong>Oh snap!</strong> <?php echo $message; ?>
		<?php } ?>
		</div>

<?php endif; ?>	
	
	
	
		<?php
		$form = $this->form;
		$form->setAttribute('action', $this->url('index', array('action' => 'subscribe')));
		$form->prepare();
		echo $this->form()->openTag($form);
		echo $this->formHidden($form->get('id'));
		?>	
	

		<div class="customer_support">
		
		<div class="form-group">
		<div class="col-md-12"><?php print $this->formRow($form->get('name'));?></div>
		</div>



		<div class="form-group">
		<div class="col-md-12"><?php print $this->formRow($form->get('email'));?></div>
		</div>



		<div class="form-group">
		<div class="col-md-12"><?php print $this->formRow($form->get('submit'));?></div>
		</div>
		
		<div class="clearfix"></div>
		
		</div>
		<?php echo $this->form()->closeTag(); ?>
		

	</div>