                                	<div class="per_content_area">
                                    	
                                        <h2 class="no_mrg">Customer Support</h2>
                                    
                                    		<div class="customer_support">
                                            	<div class="form-group">
                                                	<div class="col-md-12"><input name="" type="text" placeholder="Your Name" class="form-control"></div>
                                                </div>
                                                
                                                <div class="form-group">
                                                	<div class="col-md-6"><input name="" type="text" placeholder="Your E-mail" class="form-control"></div>
                                                    
                                                    <div class="col-md-6"><input name="" type="text" placeholder="Your Contact" class="form-control"></div>
                                                    
                                                </div>
                                                
                                                <div class="form-group">
                                                	<div class="col-md-12"><input name="" type="text" placeholder="Subject" class="form-control"></div>
                                                </div>
                                                
                                                <div class="form-group">
                                                	<div class="col-md-12"><textarea name="" cols="" rows="" placeholder="Your Content" class="form-control"></textarea></div>
                                                </div>
                                                
                                                <div class="form-group">
                                                	<div class="col-md-12"><input name="" type="submit" value="submit"></div>
                                                </div>
                                                <div class="clearfix"></div>
                                            </div>
                                        
                                    </div>